//===- RocmlirPromoteSoftmaxPrecision.cpp - Promote softmax to f32 ------===//
//
// Part of the rocMLIR Project, under the Apache License v2.0 with LLVM
// Exceptions. See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// Copyright Advanced Micro Devices, Inc.
//
//===----------------------------------------------------------------------===//
//
// This pass promotes the f16/bf16 numerator-sum (`reduce_sum(exp(...))`)
// produced by TOSA softmax patterns to f32, and opportunistically rewrites
// the two consumer chains we care about -- softmax normalization and
// log-sum-exp (LSE) -- in f32 as well.
//
// On the GPU path, `reduce_sum` is computed blockwise in f16 over small
// blocks (e.g. 32 elements), accumulating relatively little rounding error
// per block. Both the softmax normalization and the LSE computation
// (`(log2(l) + m)*ln2`) consume that blockwise sum.
//
// On the CPU path without this promotion, `reduce_sum` is a single-pass
// f16 reduction over the entire row (e.g. 384 or 1024 elements),
// accumulating much more rounding error than the GPU's blockwise approach.
// Every f16 consumer of that sum (the softmax `reciprocal` + normalize
// `mul`, and the LSE `log` + `add(max)`) then inherits and amplifies that
// error -- in particular `log` near 1 has very high relative sensitivity
// to its input.
//
// The rewrite is anchored on `tosa.reduce_sum` whose input is `tosa.exp`
// of an f16/bf16 tensor. Anchoring there (rather than on the softmax
// `mul`) means every downstream consumer benefits from the f32 sum
// automatically, and the original f16 `reduce_sum` is dead-code eliminated
// instead of being computed redundantly alongside the f32 one.
//
// For each consumer of the matched `reduce_sum`:
//   * Softmax tail (`reciprocal` -> `mul(exp, reciprocal)`) is rewritten
//     end-to-end in f32 with a single cast back to the original element
//     type before the downstream matmul -- preserving the original
//     softmax-only optimization.
//   * LSE chain (`log` and the `log + add(max)` follow-up) is rewritten in
//     f32 with the inputs cast up and the result cast back. This is the
//     LSE-specific extension: without it, `log` of the (now-precise) sum
//     would still be evaluated in f16 and lose most of the precision win.
//   * Anything else consuming the sum falls back to a single
//     `cast(reduce_sum_f32 to original-elem-type)` -- semantically
//     identical to the original f16 sum, just more accurate.
//
//===----------------------------------------------------------------------===//

#include "mlir/Conversion/RocmlirPromoteSoftmaxPrecision/RocmlirPromoteSoftmaxPrecision.h"
#include "mlir/Dialect/Rock/utility/tosaUtils.h"
#include "mlir/Dialect/Tosa/IR/TosaOps.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "llvm/ADT/STLExtras.h"

namespace mlir {
#define GEN_PASS_DEF_ROCMLIRPROMOTESOFTMAXPRECISIONPASS
#include "mlir/Conversion/RocMLIRPasses.h.inc"
} // namespace mlir

using namespace mlir;
using namespace mlir::tosa;

namespace {

/// Cast `value` to a tensor with element type `targetElemType`, preserving
/// the shape of `value`'s type. If the element type already matches, returns
/// `value` unchanged.
static Value castTo(PatternRewriter &rewriter, Location loc, Value value,
                    Type targetElemType) {
  Type srcElemType = cast<ShapedType>(value.getType()).getElementType();
  if (srcElemType == targetElemType)
    return value;
  return rock::tosa::createOpAndInfer<CastOp>(rewriter, loc, targetElemType,
                                              value);
}

/// Returns true iff `mulOp` is the softmax normalize-multiply for `expVal`
/// and `reciprocalOp`, i.e. `mul(expVal, reciprocal)` in either operand
/// order. The TOSA mul shift operand is ignored for matching; it is
/// regenerated by `getMulOp` when the rewrite happens.
static bool isSoftmaxNormalizeMul(MulOp mulOp, Value expVal,
                                  ReciprocalOp reciprocalOp) {
  Value in1 = mulOp.getInput1();
  Value in2 = mulOp.getInput2();
  Value recipResult = reciprocalOp.getOutput();
  return (in1 == expVal && in2 == recipResult) ||
         (in1 == recipResult && in2 == expVal);
}

/// Rewrite the softmax tail `reciprocal -> mul(exp, reciprocal)` in f32 and
/// replace the matched `mul` op(s) with a cast back to the original element
/// type. Returns true if at least one such tail was rewritten.
///
/// `expF32` is the f32-cast of the original f16/bf16 exp value. `sumF32` is
/// the new f32 reduce_sum. `origElemType` is the f16/bf16 type that the
/// downstream matmul still expects.
static bool rewriteSoftmaxTail(PatternRewriter &rewriter, Location loc,
                               Value expVal, Value expF32, Value sumF32,
                               Type origElemType,
                               ReciprocalOp reciprocalOp) {
  Type f32Type = rewriter.getF32Type();

  // Find every mul that uses both this reciprocal and the same exp value.
  // In practice there is exactly one, but we guard against multi-consumer
  // patterns that might appear after fusion.
  SmallVector<MulOp> normMuls;
  for (Operation *user : reciprocalOp.getOutput().getUsers())
    if (auto mulOp = dyn_cast<MulOp>(user))
      if (isSoftmaxNormalizeMul(mulOp, expVal, reciprocalOp))
        normMuls.push_back(mulOp);

  if (normMuls.empty())
    return false;

  // f32 reciprocal feeds every normalize-mul; build it once.
  auto recipF32 = rock::tosa::createOpAndInfer<ReciprocalOp>(
      rewriter, loc, f32Type, sumF32);

  for (MulOp mulOp : normMuls) {
    OpBuilder::InsertionGuard guard(rewriter);
    rewriter.setInsertionPoint(mulOp);
    auto mulF32 = rock::tosa::getMulOp(rewriter, mulOp.getLoc(), expF32,
                                       recipF32, f32Type);
    auto castBack = rock::tosa::createOpAndInfer<CastOp>(
        rewriter, mulOp.getLoc(), origElemType, mulF32);
    rewriter.replaceOp(mulOp, castBack.getResult());
  }
  return true;
}

/// Rewrite the LSE chain `log(reduce_sum) [-> add(max)]` in f32 and replace
/// the matched `log` op (and the optional add of max) with a cast back to
/// the original element type.
///
/// We promote `log` to f32 because that is the precision-critical op: `log`
/// near 1 has very high relative sensitivity to its input. When the log
/// feeds an `add` we promote that add too so the f32 log result isn't
/// truncated to the original element type before being added to max --
/// mirroring the GPU's `(log2(l) + m)*ln2` that runs entirely in the
/// softmax-acc type.
static void rewriteLseChain(PatternRewriter &rewriter, Location loc,
                            Value sumF32, Type origElemType, LogOp logOp) {
  Type f32Type = rewriter.getF32Type();

  // f32 log of the new f32 sum.
  OpBuilder::InsertionGuard guard(rewriter);
  rewriter.setInsertionPoint(logOp);
  auto logF32 = rock::tosa::createOpAndInfer<LogOp>(rewriter, logOp.getLoc(),
                                                    f32Type, sumF32);

  // Promote any AddOp consumer of the log result into f32 too. The other
  // operand (typically `reduce_max`) is cast up to f32; the final result
  // is cast back to the original element type for downstream consumers.
  SmallVector<AddOp> lseAdds;
  for (Operation *user : logOp.getOutput().getUsers())
    if (auto addOp = dyn_cast<AddOp>(user))
      lseAdds.push_back(addOp);

  for (AddOp addOp : lseAdds) {
    OpBuilder::InsertionGuard addGuard(rewriter);
    rewriter.setInsertionPoint(addOp);
    Value lhs = addOp.getInput1();
    Value rhs = addOp.getInput2();
    Value lhsF32 = (lhs == logOp.getOutput())
                       ? logF32.getResult()
                       : castTo(rewriter, addOp.getLoc(), lhs, f32Type);
    Value rhsF32 = (rhs == logOp.getOutput())
                       ? logF32.getResult()
                       : castTo(rewriter, addOp.getLoc(), rhs, f32Type);
    auto addF32 = rock::tosa::createOpAndInfer<AddOp>(
        rewriter, addOp.getLoc(), f32Type, lhsF32, rhsF32);
    auto castBack = rock::tosa::createOpAndInfer<CastOp>(
        rewriter, addOp.getLoc(), origElemType, addF32);
    rewriter.replaceOp(addOp, castBack.getResult());
  }

  // Any remaining users of the log result (no follow-up add, or extra
  // consumers beyond the add) need an f16/bf16-typed value.
  if (!logOp.getOutput().use_empty()) {
    auto castBack = rock::tosa::createOpAndInfer<CastOp>(
        rewriter, logOp.getLoc(), origElemType, logF32);
    rewriter.replaceOp(logOp, castBack.getResult());
  } else {
    rewriter.eraseOp(logOp);
  }
}

/// Match `tosa.reduce_sum` whose input is `tosa.exp` of an f16/bf16 tensor
/// and rewrite the sum in f32. Opportunistically rewrites known consumer
/// chains (softmax tail, LSE) entirely in f32; falls back to a cast back to
/// the original element type for any other consumers so semantics are
/// preserved.
struct PromoteSoftmaxReduceSumPattern : public OpRewritePattern<ReduceSumOp> {
  using OpRewritePattern::OpRewritePattern;

  LogicalResult matchAndRewrite(ReduceSumOp reduceSumOp,
                                PatternRewriter &rewriter) const override {
    auto inputType = cast<RankedTensorType>(reduceSumOp.getInput().getType());
    Type elemType = inputType.getElementType();
    if (!isa<Float16Type, BFloat16Type>(elemType))
      return failure();

    auto expOp =
        dyn_cast_or_null<ExpOp>(reduceSumOp.getInput().getDefiningOp());
    if (!expOp)
      return failure();

    Location loc = reduceSumOp.getLoc();
    Type f32Type = rewriter.getF32Type();
    Value expVal = expOp.getOutput();

    // Build the f32 cast-of-exp at the original exp's location. Multiple
    // consumers (softmax tail, LSE, fallback cast) will reuse this single
    // f32 value.
    Value expF32;
    {
      OpBuilder::InsertionGuard guard(rewriter);
      rewriter.setInsertionPointAfter(expOp);
      expF32 =
          rock::tosa::createOpAndInfer<CastOp>(rewriter, loc, f32Type, expVal);
    }

    // f32 reduce_sum (this is the actual precision-critical rewrite: it
    // replaces the single-pass f16 reduction over the whole softmax row).
    auto sumF32 = rock::tosa::createOpAndInfer<ReduceSumOp>(
        rewriter, loc, f32Type, expF32,
        rewriter.getI32IntegerAttr(reduceSumOp.getAxis()));

    // Walk consumers of the original (f16/bf16) reduce_sum and rewrite the
    // ones we recognize. Use early_inc_range because we will replace some
    // of them in-flight.
    for (Operation *user :
         llvm::make_early_inc_range(reduceSumOp.getOutput().getUsers())) {
      if (auto reciprocalOp = dyn_cast<ReciprocalOp>(user)) {
        if (rewriteSoftmaxTail(rewriter, loc, expVal, expF32, sumF32, elemType,
                               reciprocalOp)) {
          // The reciprocal itself is no longer needed by anyone we know
          // about; if any normalize-mul has consumed it the rewrite has
          // already redirected those uses. Drop it if it's dead now.
          if (reciprocalOp.getOutput().use_empty())
            rewriter.eraseOp(reciprocalOp);
        }
      } else if (auto logOp = dyn_cast<LogOp>(user)) {
        rewriteLseChain(rewriter, loc, sumF32, elemType, logOp);
      }
    }

    // Replace the original reduce_sum with `cast(sum_f32 -> orig elem
    // type)` so any unrecognized consumers (and any normalize-mul or LSE
    // chain that we couldn't fully rewrite above because their operand
    // shape didn't match) still see a value of the original type with the
    // improved precision baked in.
    auto castBack =
        rock::tosa::createOpAndInfer<CastOp>(rewriter, loc, elemType, sumF32);
    rewriter.replaceOp(reduceSumOp, castBack.getResult());
    return success();
  }
};

struct RocmlirPromoteSoftmaxPrecisionPass
    : public impl::RocmlirPromoteSoftmaxPrecisionPassBase<
          RocmlirPromoteSoftmaxPrecisionPass> {
  void runOnOperation() override {
    RewritePatternSet patterns(&getContext());
    patterns.add<PromoteSoftmaxReduceSumPattern>(&getContext());

    if (failed(applyPatternsGreedily(getOperation(), std::move(patterns))))
      return signalPassFailure();
  }
};

} // namespace
