//===- QuickTuningShardDb.h - quick-tuning shard data contract --*- C++ -*-===//
//
// Part of the rocMLIR Project, under the Apache License v2.0 with LLVM
// Exceptions. See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// The compiled-in quick-tuning database. It holds, per lookup key, the set
// cover that unknown problems sweep and, for the problems that have been
// measured, the best config that was recorded for each of them.
//
// The database is stored as one self-contained `.inc` shard per lookup key,
// generated by mlir/utils/performance/analysis/quickTuningGen.py and
// enumerated by the checked-in index QuickTuningShards.inc. Nothing is shared
// between shards: quick-tune lists are regenerated per (arch, kernel type)
// with whatever data-type coverage the measurements at hand provide, so a
// shard is rewritten whole rather than edited in place.
//
//===----------------------------------------------------------------------===//

#ifndef MLIR_DIALECT_ROCK_TUNING_QUICKTUNINGSHARDDB_H
#define MLIR_DIALECT_ROCK_TUNING_QUICKTUNINGSHARDDB_H

#include "mlir/Support/LLVM.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/StringRef.h"
#include <cstdint>

namespace mlir {
namespace rock {

/// Stands in for a config index in a problem's best-config slots when no
/// config of that kind was measured for the problem. Every shard-scoped index
/// is a `uint16_t`, which leaves vast headroom over the few hundred configs a
/// single shard holds, so the top value is free to act as the sentinel.
inline constexpr uint16_t kQuickTuningNoConfig = 0xFFFF;

/// The problem hash a caller passes when it has no problem to name, either
/// because it has no operation to take one from or because the operation's
/// problem has no spelling. Reserved: quickTuningGen.py never records it, so a
/// lookup that passes it cannot be narrowed by a problem that happens to hash
/// to zero, and "unknown problem" always means the whole set cover.
inline constexpr uint64_t kQuickTuningNoProblem = 0;

/// One lookup key's worth of quick-tuning data.
///
/// `configs` is the shard's config pool: every perf-config string the shard
/// can hand out, whether it came from the set cover or from a per-problem
/// best. `cover` and `problemConfigs` index into it.
struct QuickTuningShard {
  /// The lookup key, `<arch>_<kernelType>_<dataType>`, spelled exactly as
  /// ParamLookupTable::makeKey spells it (e.g. "gfx942_conv_f16").
  StringRef key;

  /// The config pool, as separate string literals rather than one concatenated
  /// blob: MSVC caps the length of a single string literal (C2026) and this
  /// repo builds on Windows.
  const char *const *configs;
  uint32_t numConfigs;

  /// Indices into `configs` of the set cover, in descending coverage order.
  /// This is the list an unknown problem sweeps, unchanged from the
  /// pre-sharding table.
  const uint16_t *cover;
  uint32_t numCover;

  /// Hashes of the measured problems, strictly ascending so a lookup can
  /// binary-search them, and never `kQuickTuningNoProblem`. See
  /// QuickTuningProblemKey.h for the hash.
  const uint64_t *problems;

  /// Two slots per problem: `[2 * i]` is the best non-split-K config recorded
  /// for `problems[i]` and `[2 * i + 1]` the best split-K one, either of which
  /// may be `kQuickTuningNoConfig`. Non-split-K comes first because the head
  /// of a quick-tuning list has to be legal in every fusion context.
  const uint16_t *problemConfigs;

  /// Number of measured problems, i.e. the length of `problems` and half the
  /// length of `problemConfigs`. Zero for a key with no measured problems, in
  /// which case both arrays are null and the key behaves exactly as it did
  /// before sharding.
  uint32_t numProblems;

  ArrayRef<const char *> getConfigs() const { return {configs, numConfigs}; }
  ArrayRef<uint16_t> getCover() const { return {cover, numCover}; }
  ArrayRef<uint64_t> getProblems() const { return {problems, numProblems}; }

  uint16_t getBestNonSplitK(size_t problemIdx) const {
    return problemConfigs[2 * problemIdx];
  }
  uint16_t getBestSplitK(size_t problemIdx) const {
    return problemConfigs[2 * problemIdx + 1];
  }
};

/// Every shard the index enumerates, in index order. Callers must not depend
/// on that order; the index is sorted by file name only so that its diffs stay
/// readable.
///
/// A shard has to define its arrays at namespace scope but list its entry
/// inside a `QuickTuningShard[]` initializer, so it is included twice, once
/// per phase, and brackets each phase with the matching guard:
///
///   #ifdef QUICK_TUNING_DB_ARRAYS      // the four static arrays
///   #ifdef QUICK_TUNING_DB_ENTRIES     // one `{...},` QuickTuningShard entry
///
/// Being included twice, a shard must not carry an include guard. The two
/// phases are driven from QuickTuningShardDb.cpp, which is the only file that
/// may define either macro.
ArrayRef<QuickTuningShard> getQuickTuningShards();

} // namespace rock
} // namespace mlir

#endif // MLIR_DIALECT_ROCK_TUNING_QUICKTUNINGSHARDDB_H
