//===- QuickTuningShardDb.h - quick-tuning shard data contract --*- C++ -*-===//
//
// Part of the rocMLIR Project, under the Apache License v2.0 with LLVM
// Exceptions. See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// The compiled-in per-problem quick-tuning database. The set covers used for
// unknown problems remain in QuickTuningPerfconfigs.inc.
//
// The database is stored as one self-contained `.inc` shard per lookup key,
// generated by mlir/utils/performance/analysis/quickTuningGen.py and
// enumerated by the checked-in index QuickTuningShards.inc. Nothing is shared
// between shards: quick-tune lists are regenerated per (arch, kernel type)
// with whatever data-type coverage the measurements at hand provide, so a
// shard is rewritten whole rather than edited in place.
//
//===----------------------------------------------------------------------===//

#ifndef MLIR_DIALECT_ROCK_TUNING_QUICKTUNINGSHARDDB_H
#define MLIR_DIALECT_ROCK_TUNING_QUICKTUNINGSHARDDB_H

#include "mlir/Support/LLVM.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/StringRef.h"
#include <cstdint>

namespace mlir {
namespace rock {

/// Stands in for a config index in a problem's best-config slots when no
/// config of that kind was measured for the problem. Every shard-scoped index
/// is a `uint16_t`, which leaves vast headroom over the few hundred configs a
/// single shard holds, so the top value is free to act as the sentinel.
inline constexpr uint16_t kQuickTuningNoConfig = 0xFFFF;

/// The problem hash a caller passes when it has no problem to name, either
/// because it has no operation to take one from or because the operation's
/// problem has no spelling. Reserved: quickTuningGen.py never records it, so a
/// lookup that passes it cannot be narrowed by a problem that happens to hash
/// to zero, and "unknown problem" always means the whole set cover.
inline constexpr uint64_t kQuickTuningNoProblem = 0;

/// One lookup key's worth of quick-tuning data.
///
/// `configs` is the shard-local pool of every perf-config string named by a
/// problem's top-N list. `problemConfigs` indexes into it.
struct QuickTuningShard {
  /// The lookup key, `<arch>_<kernelType>_<dataType>`, spelled exactly as
  /// ParamLookupTable::makeKey spells it (e.g. "gfx942_conv_f16").
  StringRef key;

  /// The config pool, as separate string literals rather than one concatenated
  /// blob: MSVC caps the length of a single string literal (C2026) and this
  /// repo builds on Windows.
  const char *const *configs;
  uint32_t numConfigs;

  /// Hashes of the measured problems, strictly ascending so a lookup can
  /// binary-search them, and never `kQuickTuningNoProblem`. See
  /// QuickTuningProblemKey.h for the hash.
  const uint64_t *problems;

  /// `numTopN` slots per problem, in descending measured TFlops order, padded
  /// with `kQuickTuningNoConfig` when fewer configurations were measured.
  const uint16_t *problemConfigs;

  /// Number of measured problems, i.e. the length of `problems` and half the
  /// length of `problemConfigs`. Zero for a key with no measured problems, in
  /// which case both arrays are null and the key behaves exactly as it did
  /// before sharding.
  uint32_t numProblems;
  uint16_t numTopN;

  ArrayRef<const char *> getConfigs() const { return {configs, numConfigs}; }
  ArrayRef<uint64_t> getProblems() const { return {problems, numProblems}; }

  ArrayRef<uint16_t> getProblemConfigs(size_t problemIdx) const {
    return {problemConfigs + problemIdx * numTopN, numTopN};
  }
};

/// Every shard the index enumerates, in index order. Callers must not depend
/// on that order; the index is sorted by file name only so that its diffs stay
/// readable.
///
/// A shard has to define its arrays at namespace scope but list its entry
/// inside a `QuickTuningShard[]` initializer, so it is included twice, once
/// per phase, and brackets each phase with the matching guard:
///
///   #ifdef QUICK_TUNING_DB_ARRAYS      // the three static arrays
///   #ifdef QUICK_TUNING_DB_ENTRIES     // one `{...},` QuickTuningShard entry
///
/// Being included twice, a shard must not carry an include guard. The two
/// phases are driven from QuickTuningShardDb.cpp, which is the only file that
/// may define either macro.
ArrayRef<QuickTuningShard> getQuickTuningShards();

} // namespace rock
} // namespace mlir

#endif // MLIR_DIALECT_ROCK_TUNING_QUICKTUNINGSHARDDB_H
