#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/Rock/IR/AmdArchDb.h"
#include "mlir/Dialect/Rock/IR/GemmSize.h"
#include "mlir/Dialect/Rock/IR/GetRockInfo.h"
#include "mlir/Dialect/Rock/IR/Rock.h"
#include "mlir/Dialect/Rock/IR/RockGemmGemmWrapperInterface.h"
#include "mlir/Dialect/Rock/IR/RockGemmWrapperInterface.h"
#include "mlir/Dialect/Rock/IR/RockTuningParamAttrInterface.h"
#include "mlir/Dialect/Rock/IR/RockTypes.h"
#include "mlir/Dialect/Rock/Passes.h"
#include "mlir/Dialect/Rock/Tuning/GridwiseGemmGemmParams.h"
#include "mlir/Dialect/Rock/Tuning/GridwiseGemmParams.h"
#include "mlir/Dialect/Rock/Tuning/RockTuning.h"
#include "mlir/Dialect/Rock/Tuning/UtilityParams.h"
#include "mlir/Dialect/Rock/utility/fusionUtils.h"
#include "mlir/Dialect/Rock/utility/loweringUtils.h"
#include "mlir/IR/BuiltinAttributes.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/Operation.h"
#include "mlir/IR/Types.h"
#include "mlir/Pass/Pass.h"
#include "llvm/Support/MathExtras.h"

#include "llvm/ADT/StringSet.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/LogicalResult.h"
#include "llvm/Support/raw_ostream.h"
#include <optional>

namespace mlir {
namespace rock {
#define GEN_PASS_DEF_ROCKAFFIXTUNINGPARAMETERSPASS
#include "mlir/Dialect/Rock/Passes.h.inc"
} // namespace rock
} // namespace mlir

#define DEBUG_TYPE "rock-affix-params"

using namespace mlir;
using namespace mlir::rock;

// Per-field perf-config validators. A violation is treated as a hard
// diagnostic; `markAsNotApplicable` is reserved for arch-feature mismatches.

static bool isPositivePowerOfTwo(int64_t v) {
  return v > 0 && llvm::isPowerOf2_64(static_cast<uint64_t>(v));
}

static LogicalResult validatePositivePowerOfTwo(Operation *op, StringRef name,
                                                int64_t value) {
  if (!isPositivePowerOfTwo(value))
    return op->emitError() << name << "=" << value
                           << " must be a positive power of two";
  return success();
}

static LogicalResult validatePositiveValue(Operation *op, StringRef name,
                                           int64_t value) {
  if (value <= 0)
    return op->emitError() << name << "=" << value << " must be positive";
  return success();
}

static LogicalResult validateNumCTAs(Operation *op, int64_t numCTAs) {
  if (numCTAs < 1)
    return op->emitError() << "numCTAs=" << numCTAs << " must be >= 1";
  if (!isPositivePowerOfTwo(numCTAs))
    return op->emitError() << "numCTAs=" << numCTAs
                           << " must be a positive power of two";
  StringRef arch = rock::getArchValue(op);
  int64_t maxNumCTAs = rock::getMaxNumCTAs(arch);
  if (numCTAs > maxNumCTAs)
    return op->emitError() << "numCTAs=" << numCTAs << " exceeds max ("
                           << maxNumCTAs << ") for " << arch;
  if (numCTAs != 1 && !rock::supportsMultiCTALaunch(arch))
    return op->emitError() << "numCTAs=" << numCTAs
                           << " but multi-CTA launch is not supported on "
                           << arch;
  return success();
}

// Restrict kpack to values generated by tuning and supported by the target.
// Reject configs that violate this regardless of where they came from.
static LogicalResult validateKpack(Operation *op, int64_t kpack) {
  StringRef arch = rock::getArchValue(op);
  if (kpack < 1)
    return op->emitError() << "kpack=" << kpack << " must be positive";
  int64_t maxKpack = rock::getMaxKpack(arch);
  if (kpack > maxKpack)
    return op->emitError() << "kpack=" << kpack << " exceeds max (" << maxKpack
                           << ") for " << arch;
  return success();
}

// blockSize = waveSize * numWaves, capped by `maxHardwareWorkgroupSize`.
static LogicalResult validateNumWaves(Operation *op, int64_t numWaves) {
  if (!isPositivePowerOfTwo(numWaves))
    return op->emitError() << "numWaves=" << numWaves
                           << " must be a positive power of two";
  int64_t waveSize = rock::getWaveSize(rock::getArchValue(op));
  int64_t maxNumWaves = rock::maxHardwareWorkgroupSize / waveSize;
  if (numWaves > maxNumWaves)
    return op->emitError() << "numWaves=" << numWaves
                           << " * waveSize=" << waveSize
                           << " exceeds max workgroup size ("
                           << rock::maxHardwareWorkgroupSize << ")";
  return success();
}

// 0 means "let Triton's heuristic pick"; per-arch instruction availability
// is checked by Triton itself.
static LogicalResult validateMatrixInstrNonkdim(Operation *op,
                                                int64_t matrixInstrNonkdim) {
  if (matrixInstrNonkdim != 0 && !isPositivePowerOfTwo(matrixInstrNonkdim))
    return op->emitError()
           << "matrixInstrNonkdim=" << matrixInstrNonkdim
           << " must be 0 (heuristic) or a positive power of two";
  return success();
}

// Attention's inner gemms don't support split-K (K/V split is handled via
// the `splitKV` op attribute), so require splitKFactor == 1 for AttentionOp.
static LogicalResult validateSplitKFactor(Operation *op, int64_t splitKFactor) {
  if (splitKFactor < 1)
    return op->emitError() << "splitKFactor=" << splitKFactor
                           << " must be >= 1";
  if (isa<AttentionOp>(op) && splitKFactor != 1)
    return op->emitError() << "splitKFactor=" << splitKFactor
                           << " must be 1 for attention";
  return success();
}

static LogicalResult validateNumStages(Operation *op, int64_t numStages) {
  if (numStages < 1)
    return op->emitError() << "numStages=" << numStages << " must be >= 1";
  return success();
}

// 0 means "let the backend pick"; otherwise must fit the per-arch cap.
static LogicalResult validateWavesPerEU(Operation *op, int64_t wavesPerEU) {
  if (wavesPerEU < 0)
    return op->emitError() << "wavesPerEU=" << wavesPerEU << " must be >= 0";
  StringRef arch = rock::getArchValue(op);
  int64_t maxWavesPerEU = rock::getMaxWavesPerEU(arch);
  if (wavesPerEU > maxWavesPerEU)
    return op->emitError() << "wavesPerEU=" << wavesPerEU << " exceeds max ("
                           << maxWavesPerEU << ") for " << arch;
  return success();
}

// 0 means "let `makeGroupedGridLayout` pick"; the upper bound depends on
// the runtime `mBlocks` count, so only reject negative values here.
static LogicalResult validateGridGroupSize(Operation *op,
                                           int64_t gridGroupSize) {
  if (gridGroupSize < 0)
    return op->emitError() << "gridGroupSize=" << gridGroupSize
                           << " must be >= 0";
  return success();
}

// 0 means "untiled": gemm1 keeps a single N tile spanning the whole head
// dimension. Any other value tiles gemm1's N dimension and must be a positive
// power of two.
static LogicalResult validateNPerBlockG1(Operation *op, int64_t nPerBlockG1) {
  if (nPerBlockG1 != 0 && !isPositivePowerOfTwo(nPerBlockG1))
    return op->emitError() << "nPerBlockG1=" << nPerBlockG1
                           << " must be 0 (untiled) or a positive power of two";
  return success();
}

// Single entry point: run all per-field checks via
// `RockTuningParamAttrInterface` (implemented by both `GemmParamsAttr` and
// `GemmGemmParamsAttr`). `requirePow2MN` controls whether mPerBlock/nPerBlock
// must be powers of two: gemm+gemm requires it, plain gemm only requires them
// to be positive since rock-decompose-nonpow2-tiles handles non-pow2 M/N.
// `requirePow2K` likewise controls kPerBlock: plain gemm allows non-pow2 K
// (rock-gridwise-gemm-to-blockwise decomposes it into power-of-two segments),
// while gemm+gemm and scaled gemm still require a power-of-two K tile.
static LogicalResult validatePerfConfig(Operation *op,
                                        RockTuningParamAttrInterface params,
                                        bool requirePow2MN, bool requirePow2K) {
  auto validateMN =
      requirePow2MN ? validatePositivePowerOfTwo : validatePositiveValue;
  if (failed(validateMN(op, "mPerBlock", params.getMPerBlock())))
    return failure();
  if (failed(validateMN(op, "nPerBlock", params.getNPerBlock())))
    return failure();
  if (auto gemmGemmParams = dyn_cast<GemmGemmParamsAttr>(params))
    if (failed(validateNPerBlockG1(op, gemmGemmParams.getNPerBlockG1())))
      return failure();
  auto validateK =
      requirePow2K ? validatePositivePowerOfTwo : validatePositiveValue;
  if (failed(validateK(op, "kPerBlock", params.getKPerBlock())))
    return failure();
  if (failed(validateKpack(op, params.getKpack())))
    return failure();
  if (failed(validateNumCTAs(op, params.getNumCTAs())))
    return failure();
  if (failed(validateNumWaves(op, params.getNumWaves())))
    return failure();
  if (failed(validateMatrixInstrNonkdim(op, params.getMatrixInstrNonkdim())))
    return failure();
  if (failed(validateSplitKFactor(op, params.getSplitKFactor())))
    return failure();
  if (failed(validateNumStages(op, params.getNumStages())))
    return failure();
  if (failed(validateWavesPerEU(op, params.getWavesPerEU())))
    return failure();
  if (failed(validateGridGroupSize(op, params.getGridGroupSize())))
    return failure();
  return success();
}

namespace {
struct AffixTuningParameters
    : public rock::impl::RockAffixTuningParametersPassBase<
          AffixTuningParameters> {
public:
  using rock::impl::RockAffixTuningParametersPassBase<
      AffixTuningParameters>::RockAffixTuningParametersPassBase;
  void runOnOperation() override;

private:
  // Actual implementation.
  void affixTuningParametersImpl(RockGemmWrapperInterface op);
  void affixTuningParametersImpl(RockGemmGemmWrapperInterface op);

  LogicalResult validateRockAttributes(func::FuncOp func);
};
} // anonymous namespace

LogicalResult AffixTuningParameters::validateRockAttributes(func::FuncOp func) {
  static const llvm::StringSet<> knownFuncRockAttrs = {
      EnableSplitKForTuningAttr::getMnemonic(),
      ArchAttr::getMnemonic(),
      KernelAttr::getMnemonic(),
      ConvKernelAttr::getMnemonic(),
      NumCUAttr::getMnemonic(),
      NumChipletsAttr::getMnemonic(),
      BlockSizeAttr::getMnemonic(),
      UseOptimizeEpilogueAttr::getMnemonic(),
      GridSizeAttr::getMnemonic(),
      CpuVerifierAttr::getMnemonic(),
  };
  static const llvm::StringSet<> knownArgRockAttrs = {
      PrefillAttr::getMnemonic(),
  };

  for (auto &namedAttr : func->getDiscardableAttrs()) {
    StringRef name = namedAttr.getName().getValue();
    if (!knownFuncRockAttrs.contains(name)) {
      return func.emitError() << "unknown attribute '" << name
                              << "' on function '" << func.getSymName() << "'";
    }
  }
  for (unsigned i = 0, e = func.getNumArguments(); i < e; ++i) {
    if (auto argAttrs = func.getArgAttrDict(i)) {
      for (auto &namedAttr : argAttrs) {
        StringRef name = namedAttr.getName().getValue();
        if (!knownArgRockAttrs.contains(name)) {
          return func.emitError()
                 << "unknown attribute '" << name << "' on argument " << i
                 << " of function '" << func.getSymName() << "'";
        }
      }
    }
  }
  return success();
}

void AffixTuningParameters::runOnOperation() {
  func::FuncOp func = getOperation();

  if (failed(validateRockAttributes(func)))
    return signalPassFailure();

  // currently, in rocMLIR we only support one Fusion Root per function.
  // Therefore we check for that here. Note that rocMLIR does generate multiple
  // kernels for the conv_bwd_data but that decomposition happens later in the
  // pipeline.
  uint32_t fusionRootCnt = 0;
  func.walk([&](Operation *op) {
    if (op->hasTrait<OpTrait::rock::FusionRoot>()) {
      fusionRootCnt++;
    }
  });
  if (fusionRootCnt > 1) {
    func.emitError() << "Multiple Fusion Roots detected in a single "
                        "function. This is not supported.";
    signalPassFailure();
    return;
  }
  func.walk([&](RockGemmWrapperInterface op) {
    affixTuningParametersImpl(op);
    // Make sure the op has a params attribute
    if (!op.getGemmParams().has_value()) {
      return signalPassFailure();
    }
  });
  func.walk([&](RockGemmGemmWrapperInterface op) {
    affixTuningParametersImpl(op);
    // Make sure the op has a params attribute
    if (!op.getGemm0Params().has_value() || !op.getGemm1Params().has_value()) {
      return signalPassFailure();
    }
  });
}

void AffixTuningParameters::affixTuningParametersImpl(
    RockGemmWrapperInterface op) {
  OpBuilder b(op.getContext());
  auto funcParent = op->getParentOfType<func::FuncOp>();

  auto populateParamsPtr = std::make_unique<PopulateParams>();
  auto maybeValidParams = populateParamsPtr->obtainTuningParameters(b, op);

  if (failed(maybeValidParams)) {
    LLVM_DEBUG(llvm::dbgs() << "obtainTuningParameters call fails.\n");
    return signalPassFailure();
  }
  GemmParamsAttr gemmParams = maybeValidParams.value();
  StringAttr perfConfigAttr = gemmParams.getPerfConfigAttr();

  LLVM_DEBUG(llvm::dbgs() << "affixTuningParametersImpl: perfConfig: "
                          << perfConfigAttr << "\n");

  // Scaled GEMMs are not yet handled by rock-decompose-nonpow2-tiles (M/N) nor
  // by the K decomposition in rock-gridwise-gemm-to-blockwise, so keep the
  // power-of-two M/N and K requirements for them; plain GEMMs allow both to be
  // non-pow2. Arches where the peeled K loop miscompiles keep the power-of-two
  // K requirement as well (see rock::supportsNonPow2KPerBlock).
  bool isScaledGemm = op.getScaleA() || op.getScaleB();
  bool requirePow2K =
      isScaledGemm || !rock::supportsNonPow2KPerBlock(rock::getArchValue(op));
  if (failed(validatePerfConfig(op, gemmParams, /*requirePow2MN=*/isScaledGemm,
                                /*requirePow2K=*/requirePow2K)))
    return signalPassFailure();

  auto origGemmSize = op.getGemmSize();
  auto paddedGemmSize = calculatePaddedGemmSize(
      gemmParams.getKPerBlock(), gemmParams.getMPerBlock(),
      gemmParams.getNPerBlock(), origGemmSize);
  const bool requiredPadding = !(paddedGemmSize == origGemmSize);

  int64_t gemmKBlocks = 1;
  PopulateParamsInfo info = PopulateParamsInfo::fromOp(op);
  auto maybeWrwOp = (info.kernelType == KernelType::ConvBwdWeight);
  if (maybeWrwOp && isWrWAtomicKernel(info.gemmAType, requiredPadding)) {
    auto res = calculateKBlockNum(
        info.batchSize, paddedGemmSize, gemmParams.getMPerBlock(),
        gemmParams.getNPerBlock(), gemmParams.getKPerBlock(),
        gemmParams.getKpack(), info.numCu, gemmKBlocks);

    if (failed(res)) {
      LLVM_DEBUG(llvm::dbgs()
                 << "Invalid tuning parameters for computing KBlocks.\n");
      return signalPassFailure();
    }
  }

  // Set kblocks attribute only for backward weight convolutions.
  if (auto bwdOp = dyn_cast<ConvBwdWeightOp>(op.getOperation()))
    bwdOp->setAttr(bwdOp.getKBlocksAttrName(), b.getIndexAttr(gemmKBlocks));

  int64_t waveSize = rock::getWaveSize(rock::getArchValue(op));
  int64_t blockSize = obtainBlockSize(waveSize, gemmParams);
  assert(blockSize > 0);
  op.setGemmParamsAttr(gemmParams);

  // Set attributes on the function.
  getOperation()->setAttr(rock::BlockSizeAttr::getMnemonic(),
                          b.getI32IntegerAttr(blockSize));
  getOperation()->setAttr(
      rock::UseOptimizeEpilogueAttr::getMnemonic(),
      b.getI64IntegerAttr(gemmParams.getUseOptimizeEpilogue()));

  // Check fusion legality. These checks should happen after perfConfig is
  // picked either through heuristics or user provided.
  auto fusionInfo = rock::collectFusionInfo(op->getResult(0));
  if (!fusionInfo.fusionOps.empty()) {
    if (failed(testFusionLegalityReduce(funcParent))) {
      op->emitError() << "Fusion with reduce ops is not legal on this target";
      return signalPassFailure();
    }
    if (failed(testFusionLegalityBwdDataConv(funcParent))) {
      op->emitError() << "Fusion with backward data convolution is not legal";
      return signalPassFailure();
    }
  }
  if (rock::isSplitKRequested(perfConfigAttr)) {
    if (failed(testFusionLegalitySplitK(funcParent))) {
      rock::markAsNotApplicable(op);
      op->emitError() << "Fusion with SplitK perfConfig is not legal";
      return signalPassFailure();
    }
  }
}

void AffixTuningParameters::affixTuningParametersImpl(
    RockGemmGemmWrapperInterface op) {
  OpBuilder builder(op.getContext());
  auto funcParent = op->getParentOfType<func::FuncOp>();

  // set a default one if params is not provided
  auto maybeAttnPerfConfig =
      PopulateParamsGemmGemm::obtainTuningParameters(builder, op);
  if (failed(maybeAttnPerfConfig)) {
    op.emitError() << "perf config string has an incorrect format.";
    return signalPassFailure();
  }
  auto attnPerfConfig = maybeAttnPerfConfig.value();
  StringAttr perfConfigAttr = attnPerfConfig.getPerfConfigAttr();

  if (failed(validatePerfConfig(op, attnPerfConfig, /*requirePow2MN=*/true,
                                /*requirePow2K=*/true)))
    return signalPassFailure();

  auto params =
      PopulateParamsGemmGemm::getGemmParams(builder, op, attnPerfConfig);
  if (failed(params)) {
    op.emitError() << "The provided perf config is not valid";
    return signalPassFailure();
  }
  // Check fusion legality.
  auto fusionInfo = rock::collectFusionInfo(op->getResult(0));
  if (!fusionInfo.fusionOps.empty()) {
    if (failed(testFusionLegalityReduce(funcParent))) {
      op->emitError() << "Fusion with reduce ops is not legal on this target";
      return signalPassFailure();
    }
    if (failed(testFusionLegalityBwdDataConv(funcParent))) {
      op->emitError() << "Fusion with backward data convolution is not legal";
      return signalPassFailure();
    }
  }
  if (rock::isSplitKRequested(perfConfigAttr)) {
    if (failed(testFusionLegalitySplitK(funcParent))) {
      rock::markAsNotApplicable(op);
      op->emitError() << "Fusion with SplitK perfConfig is not legal";
      return signalPassFailure();
    }
  }
  GemmParamsAttr params0, params1;
  params0 = params->first;
  params1 = params->second;
  LLVM_DEBUG(llvm::dbgs() << "params0=" << params0 << "\n");
  LLVM_DEBUG(llvm::dbgs() << "params1=" << params1 << "\n");
  op.setGemm0ParamsAttr(params0);
  op.setGemm1ParamsAttr(params1);

  // Set block size on the function (use gemm0 params since both gemms
  // share the same wave/block configuration).
  int64_t waveSize = rock::getWaveSize(rock::getArchValue(op));
  int64_t blockSize = obtainBlockSize(waveSize, params0);
  assert(blockSize > 0);
  getOperation()->setAttr(rock::BlockSizeAttr::getMnemonic(),
                          builder.getI32IntegerAttr(blockSize));
  getOperation()->setAttr(
      rock::UseOptimizeEpilogueAttr::getMnemonic(),
      builder.getI64IntegerAttr(attnPerfConfig.getUseOptimizeEpilogue()));
}
