//===- LowerCpuVerifier.cpp - Lower CPU verifier functions ----------------===//
//
// Copyright 2026 Advanced Micro Devices.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// =============================================================================
//
// This pass lowers ONLY functions marked with "rock.cpu_verifier" attribute.
// These are CPU verification functions generated by rocmlir-gen that use
// tensor semantics and need to be bufferized before general host lowering.
//
// The pass isolates each marked function into a temporary module, runs the
// lowering pipeline on it, and then moves the lowered function back. This
// ensures that NO other functions in the module are affected.
//
//===----------------------------------------------------------------------===//

#include "mlir/Conversion/Passes.h"
#include "mlir/Conversion/TensorToLinalg/TensorToLinalgPass.h"
#include "mlir/Conversion/TosaToArith/TosaToArith.h"
#include "mlir/Conversion/TosaToLinalg/TosaToLinalg.h"
#include "mlir/Conversion/TosaToSCF/TosaToSCF.h"
#include "mlir/Conversion/TosaToTensor/TosaToTensor.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Bufferization/IR/Bufferization.h"
#include "mlir/Dialect/Bufferization/Transforms/Passes.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/Linalg/Passes.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/MemRef/Transforms/Passes.h"
#include "mlir/Dialect/Rock/Passes.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/Dialect/Tosa/Transforms/Passes.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/IRMapping.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Pass/PassManager.h"
#include "mlir/Transforms/Passes.h"

#include "llvm/Support/Debug.h"

namespace mlir {
namespace rock {
#define GEN_PASS_DEF_ROCKLOWERCPUVERIFIERPASS
#include "mlir/Dialect/Rock/Passes.h.inc"
} // namespace rock
} // namespace mlir

#define DEBUG_TYPE "rock-lower-cpu-verifier"

using namespace mlir;
using namespace mlir::rock;

namespace {

/// Check if a function has the cpu_verifier attribute
static bool isCpuVerifierFunc(func::FuncOp func) {
  return func->hasAttr("rock.cpu_verifier");
}

struct RockLowerCpuVerifierPass
    : public rock::impl::RockLowerCpuVerifierPassBase<RockLowerCpuVerifierPass> {
  using RockLowerCpuVerifierPassBase::RockLowerCpuVerifierPassBase;

  void runOnOperation() override;

private:
  /// Lower a single CPU verifier function in isolation
  LogicalResult lowerSingleFunction(func::FuncOp func);
};

} // end anonymous namespace

LogicalResult RockLowerCpuVerifierPass::lowerSingleFunction(func::FuncOp func) {
  MLIRContext *ctx = &getContext();
  Location loc = func.getLoc();
  StringRef funcName = func.getName();

  LLVM_DEBUG(llvm::dbgs() << "Lowering CPU verifier function: " << funcName
                          << "\n");

  // Step 1: Create a temporary module containing only this function
  OwningOpRef<ModuleOp> tempModule = ModuleOp::create(loc);

  // Step 2: Clone the function into the temporary module
  IRMapping mapping;
  Operation *clonedOp = func->clone(mapping);
  auto clonedFunc = cast<func::FuncOp>(clonedOp);
  tempModule->push_back(clonedFunc);

  // Step 3: Build the lowering pipeline
  PassManager pm(ctx, PassManager::getAnyOpAnchorName(),
                 PassManager::Nesting::Implicit);

  // Convert TOSA ops to linalg/tensor (if any remain)
  auto &funcPm = pm.nest<func::FuncOp>();
  funcPm.addPass(createTosaToTensorPass());
  funcPm.addPass(createTosaToSCFPass());
  funcPm.addPass(createTosaToArithPass());

  // Linalg tensor optimizations
  funcPm.addPass(createLinalgElementwiseOpFusionPass());
  funcPm.addPass(createLinalgFoldUnitExtentDimsPass());

  // Canonicalize before tensor-to-linalg conversion
  funcPm.addPass(createCanonicalizerPass());

  // Convert tensor ops to linalg
  pm.addPass(createConvertTensorToLinalgPass());

  // Step 4: Run the pipeline on the temporary module ONLY
  if (failed(pm.run(*tempModule))) {
    return func.emitError("CPU verifier lowering pipeline failed for function");
  }

  // Step 5: Get the lowered function from the temporary module
  func::FuncOp loweredFunc = nullptr;
  tempModule->walk([&](func::FuncOp f) { loweredFunc = f; });

  if (!loweredFunc) {
    return func.emitError("Could not find lowered function in temporary module");
  }

  // Step 6: Replace the original function with the lowered one
  // Remove the cpu_verifier attribute from the lowered function
  loweredFunc->removeAttr("rock.cpu_verifier");

  // Clone the lowered function back to the original module
  OpBuilder builder(ctx);
  builder.setInsertionPoint(func);
  IRMapping backMapping;
  Operation *finalOp = loweredFunc->clone(backMapping);
  auto finalFunc = cast<func::FuncOp>(finalOp);
  builder.insert(finalFunc);

  // Erase the original function
  func.erase();

  LLVM_DEBUG(llvm::dbgs() << "Successfully lowered: " << funcName << "\n");
  return success();
}

void RockLowerCpuVerifierPass::runOnOperation() {
  ModuleOp module = getOperation();

  // Collect all functions with the cpu_verifier attribute
  // We collect them first because we'll be modifying the module
  SmallVector<func::FuncOp> cpuVerifierFuncs;
  module.walk([&](func::FuncOp func) {
    if (isCpuVerifierFunc(func))
      cpuVerifierFuncs.push_back(func);
  });

  if (cpuVerifierFuncs.empty()) {
    LLVM_DEBUG(llvm::dbgs() << "No CPU verifier functions found\n");
    return;
  }

  LLVM_DEBUG(llvm::dbgs() << "Found " << cpuVerifierFuncs.size()
                          << " CPU verifier function(s)\n");

  // Lower each function in isolation
  for (func::FuncOp func : cpuVerifierFuncs) {
    if (failed(lowerSingleFunction(func))) {
      return signalPassFailure();
    }
  }

  LLVM_DEBUG(llvm::dbgs() << "CPU verifier lowering completed\n");
}
