//===- LowerCpuVerifier.cpp - Lower CPU verifier functions ----------------===//
//
// Copyright 2026 Advanced Micro Devices.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// =============================================================================
//
// This pass lowers ONLY functions marked with "rock.cpu_verifier" attribute.
// These are CPU verification functions generated by rocmlir-gen that use
// tensor semantics and need to be bufferized before general host lowering.
//
// The pass uses the MLIR Transform Interpreter to apply a transform sequence
// that bufferizes and lowers the tensor operations to loops.
//
//===----------------------------------------------------------------------===//

#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Bufferization/IR/Bufferization.h"
#include "mlir/Dialect/Bufferization/TransformOps/BufferizationTransformOps.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/Func/TransformOps/FuncTransformOps.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/Linalg/TransformOps/DialectExtension.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/MemRef/TransformOps/MemRefTransformOps.h"
#include "mlir/Dialect/Rock/Passes.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/Dialect/SCF/IR/ValueBoundsOpInterfaceImpl.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/Dialect/Transform/IR/TransformDialect.h"
#include "mlir/Dialect/Vector/TransformOps/VectorTransformOps.h"
#include "mlir/Dialect/Transform/IR/TransformOps.h"
#include "mlir/Dialect/Transform/Interfaces/TransformInterfaces.h"
#include "mlir/Dialect/Transform/Transforms/TransformInterpreterUtils.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/DialectRegistry.h"
#include "mlir/IR/IRMapping.h"
#include "mlir/Parser/Parser.h"
#include "mlir/Pass/Pass.h"

#include "llvm/Support/Debug.h"

namespace mlir {
namespace rock {
#define GEN_PASS_DEF_ROCKLOWERCPUVERIFIERPASS
#include "mlir/Dialect/Rock/Passes.h.inc"
} // namespace rock
} // namespace mlir

#define DEBUG_TYPE "rock-lower-cpu-verifier"

using namespace mlir;
using namespace mlir::rock;

namespace {

/// The transform sequence to lower CPU verifier functions.
/// This is equivalent to running:
///   mlir-opt --transform-interpreter
/// with this transform module.
constexpr const char *kTransformSequence = R"mlir(
module attributes {transform.with_named_sequence} {    
  transform.named_sequence @__basic_lowering(%arg0: !transform.any_op {transform.consumed}) {

    %0 = transform.structured.match attributes{"rock.matmul"} in %arg0 : (!transform.any_op) -> !transform.any_op
    %1, %loops:4 = transform.structured.tile_using_for %0 tile_sizes [3, 32, 32, 1] : (!transform.any_op) -> (!transform.any_op, !transform.any_op, !transform.any_op, !transform.any_op, !transform.any_op)

    %func1 = transform.structured.match ops{["func.func"]} in %arg0 : (!transform.any_op) -> !transform.any_op
    %2 = transform.apply_registered_pass "canonicalize" to %func1 : (!transform.any_op) -> !transform.any_op
    %3 = transform.apply_registered_pass "lower-affine" to %2 : (!transform.any_op) -> !transform.any_op

    %10 = transform.bufferization.one_shot_bufferize layout{IdentityLayoutMap} %arg0 {bufferize_function_boundaries = false} : (!transform.any_op) -> !transform.any_op
    //%11 = transform.structured.match ops{["linalg.generic"]} in %0 : (!transform.any_op) -> !transform.any_op
    //%12 = transform.structured.convert_to_loops %1 : (!transform.any_op) -> !transform.any_op      

    // Lowering to LLVM

    %func = transform.structured.match ops{["func.func"]} in %10 : (!transform.any_op) -> !transform.any_op
    %f = transform.apply_registered_pass "convert-vector-to-scf" to %func : (!transform.any_op) -> !transform.any_op
    %f2 = transform.apply_registered_pass "convert-linalg-to-loops" to %f : (!transform.any_op) -> !transform.any_op
    %f3 = transform.apply_registered_pass "convert-scf-to-cf" to %f2 : (!transform.any_op) -> !transform.any_op
    %f4 = transform.apply_registered_pass "expand-strided-metadata" to %f3 : (!transform.any_op) -> !transform.any_op
    %f5 = transform.apply_registered_pass "lower-affine" to %f4 : (!transform.any_op) -> !transform.any_op

    transform.apply_conversion_patterns to %f5 {
      transform.apply_conversion_patterns.dialect_to_llvm "math"
      transform.apply_conversion_patterns.vector.vector_to_llvm
      transform.apply_conversion_patterns.dialect_to_llvm "memref"
      // transform.apply_conversion_patterns.func.func_to_llvm
      transform.apply_conversion_patterns.dialect_to_llvm "index"
      transform.apply_conversion_patterns.dialect_to_llvm "arith"
      transform.apply_conversion_patterns.dialect_to_llvm "cf"
    } with type_converter {
      transform.apply_conversion_patterns.memref.memref_to_llvm_type_converter
        {index_bitwidth = 64,
        use_bare_ptr = false,
        use_bare_ptr_memref_call_conv = false,
        use_opaque_pointers = true}
    } {
      legal_dialects = ["llvm"],
      partial_conversion
    } : !transform.any_op

    // Need to rematch here because:
    //   1. applying reconcile-unrealized-casts on the whole module yields the
    //      transform applies to transform, when called from a named sequence, at
    //      this time.
    //   2. apply_conversion patterns consumes the func but does not produce 
    //      a new llvm.func.
    %f6 = transform.structured.match ops{["llvm.func"]} in %10 
      : (!transform.any_op) -> !transform.any_op
    %f7 = transform.apply_registered_pass "reconcile-unrealized-casts" to %f6
      : (!transform.any_op) -> !transform.any_op

    transform.yield 
  }
  transform.named_sequence @__transform_main(%arg0: !transform.any_op {transform.consumed}) {
    transform.include @__basic_lowering failures(propagate) (%arg0) : (!transform.any_op) -> ()
    transform.yield
  }
}
)mlir";

/// Check if a function has the cpu_verifier attribute
static bool isCpuVerifierFunc(func::FuncOp func) {
  return func->hasAttr("rock.cpu_verifier");
}

struct RockLowerCpuVerifierPass
    : public rock::impl::RockLowerCpuVerifierPassBase<RockLowerCpuVerifierPass> {
  using RockLowerCpuVerifierPassBase::RockLowerCpuVerifierPassBase;

  void getDependentDialects(DialectRegistry &registry) const override {
    // Call base class to include dialects from Passes.td
    RockLowerCpuVerifierPassBase::getDependentDialects(registry);

    // Register transform dialect extensions needed for parsing the transform
    // sequence. This must be done here (not in runOnOperation) to avoid
    // thread-safety issues. The extensions provide ops like
    // transform.structured.match, transform.bufferization.one_shot_bufferize.
    linalg::registerTransformDialectExtension(registry);
    bufferization::registerTransformDialectExtension(registry);
    vector::registerTransformDialectExtension(registry);
    func::registerTransformDialectExtension(registry);
    memref::registerTransformDialectExtension(registry);

    // Register ValueBoundsOpInterface for SCF dialect, required by
    // transform.structured.tile_using_for
    scf::registerValueBoundsOpInterfaceExternalModels(registry);
  }

  void runOnOperation() override;

private:
  /// Lower a single CPU verifier function using the transform interpreter
  LogicalResult lowerSingleFunction(func::FuncOp func,
                                    ModuleOp transformModule);
};

} // end anonymous namespace

LogicalResult
RockLowerCpuVerifierPass::lowerSingleFunction(func::FuncOp func,
                                              ModuleOp transformModule) {
  MLIRContext *ctx = &getContext();
  Location loc = func.getLoc();
  StringRef funcName = func.getName();

  LLVM_DEBUG(llvm::dbgs() << "Lowering CPU verifier function: " << funcName
                          << "\n");

  // Step 1: Create a temporary module containing only this function
  OwningOpRef<ModuleOp> tempModule = ModuleOp::create(loc);

  // Step 2: Clone the function into the temporary module
  IRMapping mapping;
  Operation *clonedOp = func->clone(mapping);
  auto clonedFunc = cast<func::FuncOp>(clonedOp);
  tempModule->push_back(clonedFunc);

  // Step 3: Find the transform entry point
  transform::TransformOpInterface entryPoint =
      transform::detail::findTransformEntryPoint(*tempModule, transformModule);
  if (!entryPoint) {
    return func.emitError("Could not find transform entry point");
  }

  // Step 4: Apply the transform sequence to the temporary module
  transform::TransformOptions options;
  if (failed(transform::applyTransformNamedSequence(
          tempModule.get(), entryPoint, transformModule, options))) {
    return func.emitError("Transform interpreter failed for function");
  }

  // Step 5: Get the lowered function from the temporary module
  // After lowering to LLVM, the function is now LLVM::LLVMFuncOp
  func::FuncOp loweredFunc = nullptr;
  tempModule->walk([&](func::FuncOp f) { loweredFunc = f; });

  if (!loweredFunc) {
    return func.emitError("Could not find lowered function in temporary module");
  }

  // Step 6: Replace the original function with the lowered one
  // Clone the lowered function back to the original module
  OpBuilder builder(ctx);
  builder.setInsertionPoint(func);
  IRMapping backMapping;
  Operation *finalOp = loweredFunc->clone(backMapping);
  builder.insert(finalOp);

  // Erase the original function
  func.erase();

  LLVM_DEBUG(llvm::dbgs() << "Successfully lowered: " << funcName << "\n");
  return success();
}

void RockLowerCpuVerifierPass::runOnOperation() {
  ModuleOp module = getOperation();
  MLIRContext *ctx = &getContext();

  // Collect all functions with the cpu_verifier attribute
  // We collect them first because we'll be modifying the module
  SmallVector<func::FuncOp> cpuVerifierFuncs;
  module.walk([&](func::FuncOp func) {
    if (isCpuVerifierFunc(func))
      cpuVerifierFuncs.push_back(func);
  });

  if (cpuVerifierFuncs.empty()) {
    LLVM_DEBUG(llvm::dbgs() << "No CPU verifier functions found\n");
    return;
  }

  LLVM_DEBUG(llvm::dbgs() << "Found " << cpuVerifierFuncs.size()
                          << " CPU verifier function(s)\n");

  // Parse the transform module once for all functions
  // The transform dialect extensions are registered in getDependentDialects()
  OwningOpRef<ModuleOp> transformModule =
      parseSourceString<ModuleOp>(kTransformSequence, ctx);
  if (!transformModule) {
    emitError(UnknownLoc::get(ctx))
        << "Failed to parse transform sequence for CPU verifier lowering";
    return signalPassFailure();
  }

  // Lower each function in isolation using the transform interpreter
  for (func::FuncOp func : cpuVerifierFuncs) {
    if (failed(lowerSingleFunction(func, transformModule.get()))) {
      return signalPassFailure();
    }
  }

  // THIS IS A HUGE HACK.
  // Add declaration for memrefCopy runtime function if not already present
  // This is needed because memref.copy lowers to a call to this function
  if (!module.lookupSymbol("memrefCopy")) {
    OpBuilder builder(ctx);
    builder.setInsertionPointToStart(module.getBody());

    auto i64Type = builder.getI64Type();
    auto ptrType = LLVM::LLVMPointerType::get(ctx);
    auto voidType = LLVM::LLVMVoidType::get(ctx);
    auto funcType = LLVM::LLVMFunctionType::get(voidType, {i64Type, ptrType, ptrType});

    builder.create<LLVM::LLVMFuncOp>(module.getLoc(), "memrefCopy", funcType,
                                     LLVM::Linkage::External);
  }

  LLVM_DEBUG(llvm::dbgs() << "CPU verifier lowering completed\n");
}
