//===- LowerCpuVerifier.cpp - Lower CPU verifier functions ----------------===//
//
// Copyright 2026 Advanced Micro Devices.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// =============================================================================
//
// This pass lowers ONLY functions marked with "rock.cpu_verifier" attribute.
// These are CPU verification functions generated by rocmlir-gen that use
// tensor semantics and need to be bufferized before general host lowering.
//
// The pass uses the MLIR Transform Interpreter to apply a transform sequence
// that bufferizes and lowers the tensor operations to loops.
//
//===----------------------------------------------------------------------===//

#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Bufferization/IR/Bufferization.h"
#include "mlir/Dialect/Bufferization/TransformOps/BufferizationTransformOps.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/Func/TransformOps/FuncTransformOps.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/Linalg/TransformOps/DialectExtension.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/MemRef/TransformOps/MemRefTransformOps.h"
#include "mlir/Dialect/Rock/Passes.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/Dialect/SCF/IR/ValueBoundsOpInterfaceImpl.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/Dialect/Transform/IR/TransformDialect.h"
#include "mlir/Dialect/Vector/TransformOps/VectorTransformOps.h"
#include "mlir/Dialect/Transform/IR/TransformOps.h"
#include "mlir/Dialect/Transform/Interfaces/TransformInterfaces.h"
#include "mlir/Dialect/Transform/Transforms/TransformInterpreterUtils.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/DialectRegistry.h"
#include "mlir/IR/IRMapping.h"
#include "mlir/IR/SymbolTable.h"
#include "mlir/Parser/Parser.h"
#include "mlir/Pass/Pass.h"

#include "llvm/Support/Debug.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/raw_ostream.h"

namespace mlir {
namespace rock {
#define GEN_PASS_DEF_ROCKLOWERCPUVERIFIERPASS
#include "mlir/Dialect/Rock/Passes.h.inc"
} // namespace rock
} // namespace mlir

#define DEBUG_TYPE "rock-lower-cpu-verifier"

using namespace mlir;
using namespace mlir::rock;

namespace {

/// Transform sequence for optimization (tiling) of CPU verifier functions.
/// This sequence tiles the matmul and applies canonicalization.
/// It ends before bufferization.
constexpr const char *kOptimizationSequence = R"mlir(
module attributes {transform.with_named_sequence} {
  transform.named_sequence @__transform_main(%arg0: !transform.any_op {transform.consumed}) {
    %0 = transform.structured.match attributes {rock.matmul} in %arg0 : (!transform.any_op) -> !transform.any_op

    %transformed, %loops:3 = transform.structured.fuse %0 tile_sizes [1, 256, 64] : (!transform.any_op) -> (!transform.any_op, !transform.any_op, !transform.any_op, !transform.any_op)
    %xxx, %loop = transform.structured.tile_using_for %transformed tile_sizes [0, 0, 0, 64] : (!transform.any_op) -> (!transform.any_op, !transform.any_op)

    %microkernel, %microkernel_loops:3 = transform.structured.tile_using_for %xxx tile_sizes [0, 8, 8, 1] : (!transform.any_op) -> (!transform.any_op, !transform.any_op, !transform.any_op, !transform.any_op)

    %1 = transform.structured.match ops{["func.func"]} in %arg0 : (!transform.any_op) -> !transform.any_op
    %2 = transform.apply_registered_pass "canonicalize" to %1 : (!transform.any_op) -> !transform.any_op
    %3 = transform.apply_registered_pass "lower-affine" to %2 : (!transform.any_op) -> !transform.any_op
    transform.yield 
  }
}
)mlir";

/// Transform sequence for lowering CPU verifier functions to LLVM.
/// This sequence starts with bufferization and lowers to LLVM dialect.
constexpr const char *kLoweringSequence = R"mlir(
module attributes {transform.with_named_sequence} {
  transform.named_sequence @__transform_main(%arg0: !transform.any_op {transform.consumed}) {

    %10 = transform.bufferization.one_shot_bufferize layout{IdentityLayoutMap} %arg0 {bufferize_function_boundaries = true} : (!transform.any_op) -> !transform.any_op

    // Lowering to LLVM

    %func = transform.structured.match ops{["func.func"]} in %10 : (!transform.any_op) -> !transform.any_op
    // Bufferization is quite dumb, so it will probably insert unnecesary memref copies.
    // We use CSE + canonicalize to remove them.
    %3 = transform.apply_registered_pass "cse" to %func : (!transform.any_op) -> !transform.any_op
    %4 = transform.apply_registered_pass "canonicalize" to %3 : (!transform.any_op) -> !transform.any_op

    %f = transform.apply_registered_pass "convert-vector-to-scf" to %4 : (!transform.any_op) -> !transform.any_op
    %f2 = transform.apply_registered_pass "convert-linalg-to-loops" to %f : (!transform.any_op) -> !transform.any_op
    %f3 = transform.apply_registered_pass "convert-scf-to-cf" to %f2 : (!transform.any_op) -> !transform.any_op
    %f4 = transform.apply_registered_pass "expand-strided-metadata" to %f3 : (!transform.any_op) -> !transform.any_op
    %f5 = transform.apply_registered_pass "lower-affine" to %f4 : (!transform.any_op) -> !transform.any_op

    transform.apply_conversion_patterns to %f5 {
      transform.apply_conversion_patterns.dialect_to_llvm "math"
      transform.apply_conversion_patterns.vector.vector_to_llvm
      transform.apply_conversion_patterns.dialect_to_llvm "memref"
      // transform.apply_conversion_patterns.func.func_to_llvm
      transform.apply_conversion_patterns.dialect_to_llvm "index"
      transform.apply_conversion_patterns.dialect_to_llvm "arith"
      transform.apply_conversion_patterns.dialect_to_llvm "cf"
    } with type_converter {
      transform.apply_conversion_patterns.memref.memref_to_llvm_type_converter
        {index_bitwidth = 64,
        use_bare_ptr = false,
        use_bare_ptr_memref_call_conv = false,
        use_opaque_pointers = true}
    } {
      legal_dialects = ["llvm"],
      partial_conversion
    } : !transform.any_op

    // Need to rematch here because:
    //   1. applying reconcile-unrealized-casts on the whole module yields the
    //      transform applies to transform, when called from a named sequence, at
    //      this time.
    //   2. apply_conversion patterns consumes the func but does not produce
    //      a new llvm.func.
    %f6 = transform.structured.match ops{["llvm.func"]} in %10
      : (!transform.any_op) -> !transform.any_op
    %f7 = transform.apply_registered_pass "reconcile-unrealized-casts" to %f6
      : (!transform.any_op) -> !transform.any_op

    transform.yield
  }
}
)mlir";

/// Check if a function has the cpu_verifier attribute
static bool isCpuVerifierFunc(func::FuncOp func) {
  return func->hasAttr("rock.cpu_verifier");
}

struct RockLowerCpuVerifierPass
    : public rock::impl::RockLowerCpuVerifierPassBase<RockLowerCpuVerifierPass> {
  using RockLowerCpuVerifierPassBase::RockLowerCpuVerifierPassBase;

  void getDependentDialects(DialectRegistry &registry) const override {
    // Call base class to include dialects from Passes.td
    RockLowerCpuVerifierPassBase::getDependentDialects(registry);

    // Register transform dialect extensions needed for parsing the transform
    // sequence. This must be done here (not in runOnOperation) to avoid
    // thread-safety issues. The extensions provide ops like
    // transform.structured.match, transform.bufferization.one_shot_bufferize.
    linalg::registerTransformDialectExtension(registry);
    bufferization::registerTransformDialectExtension(registry);
    vector::registerTransformDialectExtension(registry);
    func::registerTransformDialectExtension(registry);
    memref::registerTransformDialectExtension(registry);

    // Register ValueBoundsOpInterface for SCF dialect, required by
    // transform.structured.tile_using_for
    scf::registerValueBoundsOpInterfaceExternalModels(registry);
  }

  void runOnOperation() override;

private:
  /// Dump the IR and transform sequence to /tmp for debugging
  void dumpBeforeTransform(ModuleOp targetModule, ModuleOp transformModule,
                           StringRef funcName, StringRef phaseName);

  /// Apply a single transform sequence to the temporary module
  LogicalResult applyTransformSequence(ModuleOp tempModule,
                                       ModuleOp transformModule,
                                       StringRef sequenceName);

  /// Lower a single CPU verifier function using the transform interpreter
  LogicalResult lowerSingleFunction(func::FuncOp func,
                                    ModuleOp optimizationModule,
                                    ModuleOp loweringModule);

  /// Update call sites in the module to use memref arguments instead of tensors
  /// after the function has been bufferized with bufferize_function_boundaries=true
  void updateCallSites(ModuleOp module, StringRef funcName);

  /// Unwrap nested module structure if present
  /// Some transforms may wrap their result in an additional module, which would
  /// cause subsequent transforms like one_shot_bufferize to not process the
  /// inner function
  void unwrapNestedModule(OwningOpRef<ModuleOp> &module, StringRef funcName);
};

} // end anonymous namespace

void RockLowerCpuVerifierPass::dumpBeforeTransform(ModuleOp targetModule,
                                                   ModuleOp transformModule,
                                                   StringRef funcName,
                                                   StringRef phaseName) {
  // Create filename: /tmp/cpu_verifier_<funcname>_<phase>.mlir
  std::string filename =
      "/tmp/cpu_verifier_" + funcName.str() + "_" + phaseName.str() + ".mlir";

  std::error_code ec;
  llvm::raw_fd_ostream outFile(filename, ec, llvm::sys::fs::OF_Text);

  if (ec) {
    LLVM_DEBUG(llvm::dbgs() << "Warning: Could not open dump file " << filename
                            << ": " << ec.message() << "\n");
    return;
  }

  outFile << "// =============================================================\n";
  outFile << "// CPU Verifier Dump: " << funcName << " - " << phaseName << " phase\n";
  outFile << "// =============================================================\n\n";

  outFile << "// --- Target IR (before " << phaseName << ") ---\n";
  targetModule.print(outFile);
  outFile << "\n\n";

  outFile << "// --- Transform Sequence (" << phaseName << ") ---\n";
  transformModule.print(outFile);
  outFile << "\n";

  LLVM_DEBUG(llvm::dbgs() << "Dumped IR and transform to: " << filename << "\n");
}

LogicalResult
RockLowerCpuVerifierPass::applyTransformSequence(ModuleOp tempModule,
                                                 ModuleOp transformModule,
                                                 StringRef sequenceName) {
  // Find the transform entry point
  transform::TransformOpInterface entryPoint =
      transform::detail::findTransformEntryPoint(tempModule, transformModule);
  if (!entryPoint) {
    return tempModule.emitError("Could not find transform entry point for ")
           << sequenceName;
  }

  // Apply the transform sequence to the temporary module
  transform::TransformOptions options;
  if (failed(transform::applyTransformNamedSequence(
          tempModule, entryPoint, transformModule, options))) {
    return tempModule.emitError("Transform interpreter failed for ")
           << sequenceName;
  }

  return success();
}

void RockLowerCpuVerifierPass::unwrapNestedModule(OwningOpRef<ModuleOp> &module,
                                                  StringRef funcName) {
  // Check if there's a nested module inside the outer module
  // This can happen when some transforms wrap their result in a new module
  ModuleOp nestedModule = nullptr;
  for (Operation &op : module->getBody()->getOperations()) {
    if (auto nested = dyn_cast<ModuleOp>(&op)) {
      nestedModule = nested;
      break;
    }
  }

  if (!nestedModule) {
    return; // No nested module, nothing to do
  }

  LLVM_DEBUG(llvm::dbgs() << "  Unwrapping nested module structure\n");

  // Find the function inside the nested module
  func::FuncOp funcOp = nullptr;
  nestedModule.walk([&](func::FuncOp f) {
    if (f.getName() == funcName)
      funcOp = f;
  });

  if (!funcOp) {
    // Function not found in nested module, leave as-is
    return;
  }

  // Create a new clean module with just the function
  MLIRContext *ctx = module->getContext();
  Location loc = module->getLoc();
  OwningOpRef<ModuleOp> newModule = ModuleOp::create(loc);

  // Clone the function into the new module
  OpBuilder builder(ctx);
  builder.setInsertionPointToStart(newModule->getBody());
  builder.clone(*funcOp.getOperation());

  // Replace the old module with the new one
  module = std::move(newModule);
}

void RockLowerCpuVerifierPass::updateCallSites(ModuleOp module,
                                               StringRef funcName) {
  // Find the lowered function to get its signature
  auto loweredFunc = module.lookupSymbol<func::FuncOp>(funcName);
  if (!loweredFunc) {
    LLVM_DEBUG(llvm::dbgs() << "  Could not find lowered function " << funcName
                            << "\n");
    return;
  }

  // Find all call ops that call the target function
  SmallVector<func::CallOp> callsToUpdate;
  module.walk([&](func::CallOp callOp) {
    if (callOp.getCallee() == funcName)
      callsToUpdate.push_back(callOp);
  });

  if (callsToUpdate.empty()) {
    LLVM_DEBUG(llvm::dbgs() << "  No call sites found for " << funcName << "\n");
    return;
  }

  LLVM_DEBUG(llvm::dbgs() << "  Updating " << callsToUpdate.size()
                          << " call site(s) for " << funcName << "\n");

  for (func::CallOp callOp : callsToUpdate) {
    OpBuilder builder(callOp);
    Location loc = callOp.getLoc();

    // Collect the source memrefs from the to_tensor operands
    SmallVector<Value> memrefArgs;
    SmallVector<bufferization::ToTensorOp> toTensorOps;

    for (Value operand : callOp.getOperands()) {
      auto toTensorOp = operand.getDefiningOp<bufferization::ToTensorOp>();
      if (toTensorOp) {
        memrefArgs.push_back(toTensorOp.getOperand());
        toTensorOps.push_back(toTensorOp);
      } else {
        // If the operand is not from a to_tensor, it might already be a memref
        // or something else - this shouldn't happen in our expected pattern
        LLVM_DEBUG(llvm::dbgs()
                   << "  Warning: operand is not from to_tensor: " << operand
                   << "\n");
        memrefArgs.push_back(operand);
      }
    }

    // Create a new call with the lowered function's return types
    // With bufferize_function_boundaries=true, the function signature changes
    // from (tensor, tensor, tensor) -> tensor to (memref, memref, memref) -> memref
    auto newCall = builder.create<func::CallOp>(
        loc, funcName, loweredFunc.getResultTypes(), memrefArgs);

    // Find and remove the to_buffer and copy ops that use the old result
    // The new call returns a memref directly, so we don't need to_buffer anymore
    if (!callOp.getResults().empty()) {
      Value oldResult = callOp.getResult(0);
      for (Operation *user : llvm::make_early_inc_range(oldResult.getUsers())) {
        if (auto toBufferOp = dyn_cast<bufferization::ToBufferOp>(user)) {
          // Replace uses of to_buffer result with the new call's result
          // (if the function returns a memref)
          if (!newCall.getResults().empty()) {
            toBufferOp.getResult().replaceAllUsesWith(newCall.getResult(0));
          }
          // Find and remove the copy that uses the to_buffer result
          Value buffer = toBufferOp.getResult();
          for (Operation *bufUser :
               llvm::make_early_inc_range(buffer.getUsers())) {
            if (auto copyOp = dyn_cast<memref::CopyOp>(bufUser)) {
              copyOp.erase();
            }
          }
          toBufferOp.erase();
        }
      }
    }

    // Erase the old call
    callOp.erase();

    // Erase the to_tensor ops if they have no other uses
    for (auto toTensorOp : toTensorOps) {
      if (toTensorOp.use_empty())
        toTensorOp.erase();
    }
  }
}

LogicalResult
RockLowerCpuVerifierPass::lowerSingleFunction(func::FuncOp func,
                                              ModuleOp optimizationModule,
                                              ModuleOp loweringModule) {
  MLIRContext *ctx = &getContext();
  Location loc = func.getLoc();
  StringRef funcName = func.getName();

  LLVM_DEBUG(llvm::dbgs() << "Lowering CPU verifier function: " << funcName
                          << "\n");

  // Step 1: Create a temporary module containing only this function
  OwningOpRef<ModuleOp> tempModule = ModuleOp::create(loc);

  // Step 2: Clone the function into the temporary module
  IRMapping mapping;
  Operation *clonedOp = func->clone(mapping);
  auto clonedFunc = cast<func::FuncOp>(clonedOp);
  tempModule->push_back(clonedFunc);

  // Step 3: Apply the optimization sequence (tiling)
  LLVM_DEBUG(llvm::dbgs() << "  Applying optimization sequence...\n");
  dumpBeforeTransform(tempModule.get(), optimizationModule, funcName,
                      "optimization");
  if (failed(applyTransformSequence(tempModule.get(), optimizationModule,
                                    "optimization"))) {
    return func.emitError("Optimization transform failed for function");
  }

  // Step 3b: Unwrap any nested module structure created by the transform
  // Some transforms may wrap the result in an additional module, which would
  // cause subsequent transforms like one_shot_bufferize to not process the
  // inner function
  unwrapNestedModule(tempModule, funcName);

  // Step 4: Apply the lowering sequence (bufferization + LLVM lowering)
  LLVM_DEBUG(llvm::dbgs() << "  Applying lowering sequence...\n");
  dumpBeforeTransform(tempModule.get(), loweringModule, funcName, "lowering");
  if (failed(applyTransformSequence(tempModule.get(), loweringModule,
                                    "lowering"))) {
    return func.emitError("Lowering transform failed for function");
  }

  // Step 5: Get the lowered function from the temporary module
  // After lowering to LLVM, the function is now LLVM::LLVMFuncOp
  func::FuncOp loweredFunc = nullptr;
  tempModule->walk([&](func::FuncOp f) { loweredFunc = f; });

  if (!loweredFunc) {
    return func.emitError("Could not find lowered function in temporary module");
  }

  // Step 6: Replace the original function with the lowered one
  ModuleOp parentModule = func->getParentOfType<ModuleOp>();
  OpBuilder builder(ctx);
  builder.setInsertionPointToStart(parentModule.getBody());

  // Copy all top-level operations from tempModule to parentModule
  // (globals, function declarations, etc.) using SymbolOpInterface for genericity
  for (Operation &op : tempModule->getBody()->getOperations()) {
    // Skip module terminator
    if (op.hasTrait<OpTrait::IsTerminator>())
      continue;

    // Check if this is a symbol-defining operation
    if (auto symbolOp = dyn_cast<SymbolOpInterface>(&op)) {
      StringRef symName = symbolOp.getName();

      // Skip the lowered function itself (we handle it separately below)
      if (symName == funcName)
        continue;

      // Check if symbol already exists in parent module
      Operation *existing = parentModule.lookupSymbol(symName);
      if (existing) {
        // Special case: replace func.func with llvm.func (LLVM version is preferred)
        if (isa<func::FuncOp>(existing) && isa<LLVM::LLVMFuncOp>(&op)) {
          existing->erase();
        } else {
          // Symbol already exists, skip to avoid duplicates
          continue;
        }
      }

      builder.clone(op);
      LLVM_DEBUG(llvm::dbgs() << "  Copied symbol: " << symName << "\n");
    }
  }

  // Clone the lowered function back to the original module
  builder.setInsertionPoint(func);
  IRMapping backMapping;
  Operation *finalOp = loweredFunc->clone(backMapping);
  builder.insert(finalOp);

  // Erase the original function
  func.erase();

  // Step 7: Update call sites to use memref arguments instead of tensors
  // This is needed because bufferize_function_boundaries=true changes the
  // function signature from tensors to memrefs
  updateCallSites(parentModule, funcName);

  LLVM_DEBUG(llvm::dbgs() << "Successfully lowered: " << funcName << "\n");
  return success();
}

void RockLowerCpuVerifierPass::runOnOperation() {
  ModuleOp module = getOperation();
  MLIRContext *ctx = &getContext();

  // Collect all functions with the cpu_verifier attribute
  // We collect them first because we'll be modifying the module
  SmallVector<func::FuncOp> cpuVerifierFuncs;
  module.walk([&](func::FuncOp func) {
    if (isCpuVerifierFunc(func))
      cpuVerifierFuncs.push_back(func);
  });

  if (cpuVerifierFuncs.empty()) {
    LLVM_DEBUG(llvm::dbgs() << "No CPU verifier functions found\n");
    return;
  }

  LLVM_DEBUG(llvm::dbgs() << "Found " << cpuVerifierFuncs.size()
                          << " CPU verifier function(s)\n");

  // Parse the optimization transform module (tiling)
  // The transform dialect extensions are registered in getDependentDialects()
  OwningOpRef<ModuleOp> optimizationModule =
      parseSourceString<ModuleOp>(kOptimizationSequence, ctx);
  if (!optimizationModule) {
    emitError(UnknownLoc::get(ctx))
        << "Failed to parse optimization transform sequence for CPU verifier";
    return signalPassFailure();
  }

  // Parse the lowering transform module (bufferization + LLVM)
  OwningOpRef<ModuleOp> loweringModule =
      parseSourceString<ModuleOp>(kLoweringSequence, ctx);
  if (!loweringModule) {
    emitError(UnknownLoc::get(ctx))
        << "Failed to parse lowering transform sequence for CPU verifier";
    return signalPassFailure();
  }

  // Lower each function in isolation using the transform interpreter
  for (func::FuncOp func : cpuVerifierFuncs) {
    if (failed(lowerSingleFunction(func, optimizationModule.get(),
                                   loweringModule.get()))) {
      return signalPassFailure();
    }
  }

  // Ensure memrefCopy declaration exists if any llvm.call @memrefCopy was generated
  // The MemRefToLLVM conversion generates calls to memrefCopy but doesn't create
  // the declaration automatically
  bool hasMemrefCopyCall = false;
  module.walk([&](LLVM::CallOp callOp) {
    if (callOp.getCallee() && *callOp.getCallee() == "memrefCopy")
      hasMemrefCopyCall = true;
  });

  if (hasMemrefCopyCall && !module.lookupSymbol<LLVM::LLVMFuncOp>("memrefCopy")) {
    OpBuilder builder(ctx);
    builder.setInsertionPointToStart(module.getBody());

    // memrefCopy signature: void memrefCopy(i64 elemSize, ptr src, ptr dst)
    auto ptrType = LLVM::LLVMPointerType::get(ctx);
    auto i64Type = IntegerType::get(ctx, 64);
    auto voidType = LLVM::LLVMVoidType::get(ctx);
    auto funcType = LLVM::LLVMFunctionType::get(voidType, {i64Type, ptrType, ptrType});

    builder.create<LLVM::LLVMFuncOp>(module.getLoc(), "memrefCopy", funcType,
                                     LLVM::Linkage::External);
    LLVM_DEBUG(llvm::dbgs() << "Created memrefCopy declaration\n");
  }

  LLVM_DEBUG(llvm::dbgs() << "CPU verifier lowering completed\n");
}
