//===- Passes.h - Linalg pass entry points ----------------------*- C++ -*-===//
//
// Part of the MLIR Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// This header file defines prototypes that expose pass constructors.
//
//===----------------------------------------------------------------------===//

#ifndef MLIR_DIALECT_ROCK_PASSES_H_
#define MLIR_DIALECT_ROCK_PASSES_H_

#include "mlir/Pass/Pass.h"
#include "mlir/Support/LLVM.h"
#include "llvm/ADT/ArrayRef.h"

namespace mlir {
namespace rock {

#define GEN_PASS_DECL_ROCKAFFIXTUNINGPARAMETERSPASS
#define GEN_PASS_DECL_ROCKCONVTOGEMMPASS
#define GEN_PASS_DECL_ROCKFOLDBROADCASTPASS
#define GEN_PASS_DECL_ROCKLOWERREDUCEPASS
#define GEN_PASS_DECL_ROCKREGULARIZEINTERGEMMFUSIONPASS
#define GEN_PASS_DECL_ROCKREGULARIZEOUTPUTPASS
#define GEN_PASS_DECL_ROCKGEMMTOGRIDWISEPASS
#define GEN_PASS_DECL_ROCKATTNTOGRIDWISEPASS
#define GEN_PASS_DECL_ROCKGRIDWISEGEMMTOBLOCKWISEPASS
#define GEN_PASS_DECL_ROCKGRIDWISEATTNTOBLOCKWISEPASS
#define GEN_PASS_DECL_ROCKVIEWTOTRANSFORMPASS
#define GEN_PASS_DECL_ROCKDETECTFLASHDECODINGPASS
#define GEN_PASS_DECL_ROCKFUSIONSPLITKREGULARIZATIONPASS
#define GEN_PASS_DECL_ROCKLEGALIZEFLOATTYPESPASS
#define GEN_PASS_DECL_ROCKLOWERBLOCKWISETOPTRPASS
#define GEN_PASS_DECL_ROCKPRESERVEMASKEDLOADSEMANTICSPASS
#define GEN_PASS_DECL_ROCKCOLLAPSECONTIGUOUSMERGESPASS
#define GEN_PASS_DECL_ROCKTRANSFORMSINVARIANTCODEMOTIONPASS
#define GEN_PASS_DECL_ROCKTRANSFORMSTOPOINTERARITHPASS
#define GEN_PASS_DECL_ROCKTOTTIRPASS
#define GEN_PASS_DECL_ROCKINSERTOUTPUTSTORESPASS
#define GEN_PASS_DECL_ROCKSERIALIZEHOSTFUNCSPASS
#define GEN_PASS_DECL_ROCKFUNCTOTRITONFUNCPASS
#define GEN_PASS_DECL_RESOLVEKERNELLAUNCHPARAMSPASS
#define GEN_PASS_DECL_TRITONTOHSACOPASS
#define GEN_PASS_DECL_ROCKEMITGPUBINARYPASS
#define GEN_PASS_DECL_ROCKALLOWFASTMATHFLAGSPASS
#define GEN_PASS_DECL_ROCKINSERTOUTPUTFUSIONLOADSPASS
#define GEN_PASS_DECL_ROCKREGULARIZEINPUTPASS
#define GEN_PASS_DECL_ROCKLOWERLOADSPASS
#define GEN_PASS_DECL_ROCKTOSATOELEMENTWISEPASS
#define GEN_PASS_DECL_ROCKFLATTENTOSAFUNCARGSPASS
#define GEN_PASS_DECL_ROCKLOWERSTORESPASS
#define GEN_PASS_DECL_ROCKCONVERTNARROWTYPESIGNATURESPASS
#define GEN_PASS_DECL_ROCKEMULATENARROWTYPESPASS
#define GEN_PASS_DECL_ROCKSORTDIMENSIONSMEMORYLAYOUTPASS
#define GEN_PASS_DECL_ROCKADDTRITONMETADATAPASS
#define GEN_PASS_DECL_ROCKSETMATMULOUTPUTTRANSPOSEPASS
#define GEN_PASS_DECL_ROCKANALYZEMEMORYUSEPASS
#define GEN_PASS_DECL_ROCKPREPARELLVMPASS
#define GEN_PASS_DECL_ROCKDECOMPOSENONPOW2TILESPASS
#define GEN_PASS_REGISTRATION
#include "mlir/Dialect/Rock/Passes.h.inc"

} // namespace rock
} // namespace mlir

#endif // MLIR_DIALECT_ROCK_PASSES_H_
