//===- LowerCpuVerifier.cpp - Lower CPU verifier functions ----------------===//
//
// Copyright 2026 Advanced Micro Devices.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// =============================================================================
//
// This pass lowers ONLY functions marked with "rock.cpu_verifier" attribute.
// These are CPU verification functions generated by rocmlir-gen.
//
// The pass uses the MLIR Transform Interpreter to apply transform sequences
// that tile, vectorize, and lower operations to LLVM. It runs in two phases:
// - Phase 1: tiling, vectorization, unroll (before whole-module bufferization)
// - Phase 2: lowerToLLVM (after whole-module bufferization)
//
// Functions are isolated using detach/reattach to run transforms on each
// verifier function independently.
//
//===----------------------------------------------------------------------===//

#include "Schedules.h"
#include "Schedules/ScheduleUtils.h"
#include "Schedules/TilingSchedule.h"

#include "mlir/Conversion/CPU/Passes.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Bufferization/IR/Bufferization.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/Rock/IR/Rock.h"
#include "mlir/Dialect/Rock/utility/tritonUtils.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/Dialect/Transform/IR/TransformDialect.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/Pass/Pass.h"
#include "mlir/utils/DetachReattach.h"

#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/ScopeExit.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/raw_ostream.h"

namespace mlir {
namespace cpu {
#define GEN_PASS_DEF_CPULOWERVERIFIERPASS
#include "mlir/Conversion/CPU/Passes.h.inc"
} // namespace cpu
} // namespace mlir

#define DEBUG_TYPE "cpu-lower-verifier"

using namespace mlir;
using namespace mlir::cpu;

namespace {

/// Return true if `op`'s iterator types match the matmul signature defined
/// by `cpu::getMatmulIteratorTypes()`. Sharing the signature with the
/// transform-side matchers keeps the policy decisions made here in lockstep
/// with what the schedule actually targets.
static bool isMatmulIteratorTypes(linalg::GenericOp op) {
  SmallVector<utils::IteratorType> iters = op.getIteratorTypesArray();
  return llvm::ArrayRef(iters) == cpu::getMatmulIteratorTypes();
}

/// Return the largest value in `candidates` that divides `dim` exactly.
/// Falls back to `fallback` if none of the candidates divide. `candidates`
/// is expected to be sorted largest-first.
static int64_t pickDivisibleTile(int64_t dim, ArrayRef<int64_t> candidates,
                                 int64_t fallback) {
  for (int64_t c : candidates)
    if (c > 0 && dim % c == 0)
      return c;
  return fallback;
}

/// Return `true` when `dim` is statically known and is a clean multiple of
/// `tile`. Dynamic dims are treated as non-divisible because we can't
/// prove the property at compile time -- the schedule must handle the
/// remainder explicitly in that case.
static bool isStaticallyDivisible(int64_t dim, int64_t tile) {
  return !ShapedType::isDynamic(dim) && tile > 0 && dim % tile == 0;
}

/// Identify the (M, N, K) iter-space dims of a 3-D matmul-shaped
/// `linalg.generic`. The matmul matcher only constrains the iter-type
/// signature ((parallel, parallel, reduction) in some order), not the
/// position of each iter dim within the iter-space -- the order depends
/// on which path produced the op (rocmlir-gen GEMM vs.
/// fused-conv-to-matmul collapse), so we infer the roles from the
/// operand-map structure:
///
/// - The reduction iter dim is K.
/// - The parallel iter dim that appears in the *first input*'s map (LHS)
///   is M; the other parallel dim is N.
///
/// Returns `failure()` if `op` doesn't have exactly two inputs / one
/// output / the expected number of iter dims, or if the maps aren't
/// projected permutations using single iter-space symbols.
struct MatmulDims {
  unsigned mDim;
  unsigned nDim;
  unsigned kDim;
};

static FailureOr<MatmulDims> classifyMatmulDims(linalg::GenericOp op) {
  if (op.getNumDpsInputs() != 2 || op.getNumDpsInits() != 1)
    return failure();

  SmallVector<utils::IteratorType> iters = op.getIteratorTypesArray();
  if (llvm::ArrayRef(iters) != cpu::getMatmulIteratorTypes())
    return failure();

  auto findReductionDim = [&]() -> std::optional<unsigned> {
    for (auto [i, it] : llvm::enumerate(iters))
      if (it == utils::IteratorType::reduction)
        return static_cast<unsigned>(i);
    return std::nullopt;
  };
  std::optional<unsigned> kDim = findReductionDim();
  if (!kDim)
    return failure();

  // Collect iter dims used by the LHS input map. The parallel dim that
  // shows up in LHS is M, the other parallel dim is N.
  AffineMap lhsMap = op.getMatchingIndexingMap(op.getDpsInputOperand(0));
  llvm::SmallSet<unsigned, 4> lhsDims;
  for (AffineExpr e : lhsMap.getResults()) {
    auto dimE = dyn_cast<AffineDimExpr>(e);
    if (!dimE)
      return failure();
    lhsDims.insert(dimE.getPosition());
  }

  std::optional<unsigned> mDim, nDim;
  for (auto [i, it] : llvm::enumerate(iters)) {
    if (it != utils::IteratorType::parallel)
      continue;
    if (lhsDims.contains(static_cast<unsigned>(i)))
      mDim = static_cast<unsigned>(i);
    else
      nDim = static_cast<unsigned>(i);
  }
  if (!mDim || !nDim)
    return failure();

  return MatmulDims{*mDim, *nDim, *kDim};
}

/// Inspect the CPU verifier function `func` and choose tile sizes for its
/// matmul-shaped `linalg.generic`. Returns `std::nullopt` only when no
/// matmul-shaped op is found in the function -- in which case the caller
/// should fall back to the default schedule.
///
/// Policy: pick the largest tile in a candidate ladder that divides the
/// corresponding loop dim cleanly; if none divides (or the dim is
/// dynamic), fall back to `MatmulTileSizes::kVectorSize` and record the
/// dim as non-divisible via the `*Divisible` flags on `MatmulTileSizes`.
/// The schedule uses those flags to decide how to handle the partial
/// last iteration (peel, mask, scalar fallback, ...).
static std::optional<MatmulTileSizes> chooseMatmulTileSizes(func::FuncOp func) {
  constexpr int64_t vectorSize = MatmulTileSizes::kVectorSize;
  linalg::GenericOp matmul;
  func.walk([&](linalg::GenericOp g) {
    if (isMatmulIteratorTypes(g))
      matmul = g;
  });
  if (!matmul)
    return std::nullopt;

  // Recover (M, N, K) from the operand maps rather than assuming a
  // positional convention -- the rocmlir-gen GEMM and the
  // fused-conv-to-matmul collapse don't necessarily emit dims in the
  // same iter-space order, but the role of each dim is unambiguous from
  // the maps.
  FailureOr<MatmulDims> dims = classifyMatmulDims(matmul);
  if (failed(dims))
    return std::nullopt;

  SmallVector<int64_t, 4> loopRanges = matmul.getStaticLoopRanges();
  assert(loopRanges.size() == cpu::getMatmulIteratorTypes().size() &&
         "matmul matcher should have ensured a 3-D iteration space");

  int64_t M = loopRanges[dims->mDim];
  int64_t N = loopRanges[dims->nDim];
  int64_t K = loopRanges[dims->kDim];

  // TODO(AIROCMLIR-812): Determine these values based on the target
  // architecture.
  static constexpr int64_t mLadder[] = {512, 256, 128, 64, 32, 16, 8};
  static constexpr int64_t nLadder[] = {16, 8};
  static constexpr int64_t kLadder[] = {784, 392, 196, 128, 64, 32, 16, 8};

  MatmulTileSizes t;
  t.mFuse = pickDivisibleTile(M, mLadder, vectorSize);
  t.nFuse = pickDivisibleTile(N, nLadder, vectorSize);
  t.kTile = pickDivisibleTile(K, kLadder, vectorSize);
  t.microTileM = vectorSize;
  t.microTileN = vectorSize;
  t.microTileK = vectorSize;
  t.mDivisible = isStaticallyDivisible(M, t.mFuse);
  t.nDivisible = isStaticallyDivisible(N, t.nFuse);
  t.kDivisible = isStaticallyDivisible(K, t.kTile);
  t.mDim = dims->mDim;
  t.nDim = dims->nDim;
  t.kDim = dims->kDim;

  return t;
}

/// Describes a single transform step in the lowering pipeline.
struct TransformStep {
  ModuleOp module; // The transform module to apply.
  StringRef name;  // Name of this step (e.g., "tiling", "vectorization").
};

struct CpuLowerVerifierPass
    : public cpu::impl::CpuLowerVerifierPassBase<CpuLowerVerifierPass> {
  using CpuLowerVerifierPassBase::CpuLowerVerifierPassBase;

  void getDependentDialects(DialectRegistry &registry) const override {
    // Call base class to include dialects from Passes.td
    CpuLowerVerifierPassBase::getDependentDialects(registry);

    // Register all transform dialect extensions needed for the schedules
    registerScheduleDialectExtensions(registry);
  }

  void runOnOperation() override;

private:
  /// Dump the IR and transform sequence to /tmp for debugging
  void dumpBeforeTransform(ModuleOp targetModule, ModuleOp transformModule,
                           StringRef funcName, StringRef phaseName);

  /// Apply one transform step (pre-sequence + step + post-sequence) to
  /// `moduleRef`. Used to build the optimization pipeline incrementally
  /// so we can run `fusedConvToMatmul` before deciding tile sizes.
  LogicalResult applyTransformStep(OwningOpRef<ModuleOp> &moduleRef,
                                   const TransformStep &step,
                                   const TransformSchedules &schedules,
                                   func::FuncOp func);

  /// Lower a single CPU verifier function using the transform interpreter
  LogicalResult lowerSingleFunction(func::FuncOp func,
                                    const TransformSchedules &schedules);
};

} // end anonymous namespace

void CpuLowerVerifierPass::dumpBeforeTransform(ModuleOp targetModule,
                                               ModuleOp transformModule,
                                               StringRef funcName,
                                               StringRef phaseName) {
  // Only dump if dump-schedules-path option was specified
  if (dumpSchedulesPath.empty())
    return;

  assert(targetModule && transformModule &&
         "dumpBeforeTransform requires non-null target and transform modules");

  // Use the path specified by the pass option
  std::string dumpDir = dumpSchedulesPath;
  std::error_code ec = llvm::sys::fs::create_directory(dumpDir);
  if (ec && ec != std::errc::file_exists) {
    LLVM_DEBUG(llvm::dbgs() << "Warning: Could not create dump directory "
                            << dumpDir << ": " << ec.message() << "\n");
    return;
  }

  // Create filename: cpu_dump/cpu_verifier_<funcname>_<phase>.mlir
  std::string filename = dumpDir + "/cpu_verifier_" + funcName.str() + "_" +
                         phaseName.str() + ".mlir";

  llvm::raw_fd_ostream outFile(filename, ec, llvm::sys::fs::OF_Text);

  if (ec) {
    LLVM_DEBUG(llvm::dbgs() << "Warning: Could not open dump file " << filename
                            << ": " << ec.message() << "\n");
    return;
  }

  outFile
      << "// =============================================================\n";
  outFile << "// CPU Verifier Dump: " << funcName << " - " << phaseName
          << " phase\n";
  outFile
      << "// =============================================================\n\n";

  outFile << "// --- Target IR (before " << phaseName << ") ---\n";
  targetModule.print(outFile);
  outFile << "\n\n";

  outFile << "// --- Transform Sequence (" << phaseName << ") ---\n";
  transformModule.print(outFile);
  outFile << "\n";

  LLVM_DEBUG(llvm::dbgs() << "Dumped IR and transform to: " << filename
                          << "\n");
}

/// Apply one transform step (pre + main + post) to `moduleRef`. Returns
/// `failure()` and leaves a diagnostic on `func` if any sub-sequence
/// fails. The caller is responsible for `reattachFuncs` cleanup.
LogicalResult CpuLowerVerifierPass::applyTransformStep(
    OwningOpRef<ModuleOp> &moduleRef, const TransformStep &step,
    const TransformSchedules &schedules, func::FuncOp func) {
  if (!step.module) {
    LLVM_DEBUG(llvm::dbgs()
               << "    Skipping " << step.name << " (no schedule module)\n");
    return success();
  }
  ModuleOp module = moduleRef.get();
  StringRef funcName = func.getName();

  // Pre-sequence.
  std::string prePhaseName = "pre_" + step.name.str();
  LLVM_DEBUG(llvm::dbgs() << "    Applying " << prePhaseName << "...\n");
  dumpBeforeTransform(module, schedules.preModule.get(), funcName,
                      prePhaseName);
  if (failed(applyTransformSequence(moduleRef, schedules.preModule.get(), "pre",
                                    funcName)))
    return func.emitError("Pre transform failed before ") << step.name;

  // Main transform.
  LLVM_DEBUG(llvm::dbgs() << "    Applying " << step.name << "...\n");
  dumpBeforeTransform(module, step.module, funcName, step.name);
  if (failed(
          applyTransformSequence(moduleRef, step.module, step.name, funcName)))
    return func.emitError("Transform failed at ") << step.name;

  // Post-sequence.
  std::string postPhaseName = "post_" + step.name.str();
  LLVM_DEBUG(llvm::dbgs() << "    Applying " << postPhaseName << "...\n");
  dumpBeforeTransform(module, schedules.postModule.get(), funcName,
                      postPhaseName);
  if (failed(applyTransformSequence(moduleRef, schedules.postModule.get(),
                                    "post", funcName)))
    return func.emitError("Post transform failed after ") << step.name;
  return success();
}

LogicalResult
CpuLowerVerifierPass::lowerSingleFunction(func::FuncOp func,
                                          const TransformSchedules &schedules) {
  StringRef funcName = func.getName();
  ModuleOp module = func->getParentOfType<ModuleOp>();

  LLVM_DEBUG(llvm::dbgs() << "Lowering CPU verifier function: " << funcName
                          << "\n");

  // Step 1: Detach all functions except the target function.
  // Other module-level operations (globals, etc.) are left in place.
  // Stubs are created to keep symbol references valid during transformation.
  auto shouldDetach = [&](func::FuncOp f) { return f.getName() != funcName; };

  DetachedFuncs detached = detachFuncs(module, shouldDetach);
  LLVM_DEBUG(llvm::dbgs() << "  Detached " << detached.entries.size()
                          << " functions for isolation\n");

  // We need to wrap the module in OwningOpRef for applyTransformSequence
  // but we don't own it, so we use a non-owning reference pattern.
  OwningOpRef<ModuleOp> moduleRef(module);
  llvm::scope_exit cleanup([&] {
    (void)moduleRef.release();
    reattachFuncs(module, detached);
  });

  if (phase == CPU_PHASE_OPTIMIZE) {
    // Optimization phase splits into two stages around `chooseMatmulTileSizes`:
    //
    //   Stage 1 -- shape normalization
    //     Run `fusedConvToMatmul` first. For functions that came out of
    //     `cpu-conv-to-gemm` this rewrites the 8-D `rock.cpu_fused_conv`
    //     into a 3-D matmul-shaped `linalg.generic` (and folds the
    //     unit-extent batch/group dims). For plain GEMM verifiers the
    //     schedule is a no-op.
    //
    //   Stage 2 -- tile / vectorize / unroll.
    if (failed(applyTransformStep(
            moduleRef,
            {schedules.fusedConvToMatmulModule.get(), "fusedConvToMatmul"},
            schedules, func)))
      return failure();

    OwningOpRef<ModuleOp> perFuncTiling;
    if (auto t = chooseMatmulTileSizes(func)) {
      LLVM_DEBUG(llvm::dbgs() << "  Chose matmul tile sizes for " << funcName
                              << ": M=" << t->mFuse << " N=" << t->nFuse
                              << " K=" << t->kTile << "\n");
      perFuncTiling = buildTilingSchedule(&getContext(), *t);
    } else {
      LLVM_DEBUG(llvm::dbgs() << "  Using default matmul tile sizes for "
                              << funcName << " (no matmul shape)\n");
      perFuncTiling = buildTilingSchedule(&getContext());
    }
    if (!perFuncTiling)
      return func.emitError("Failed to build per-function tiling schedule");

    SmallVector<TransformStep> stage2 = {
        {perFuncTiling.get(), "tiling"},
        {schedules.vectorizationModule.get(), "vectorization"},
        {schedules.unrollModule.get(), "unroll"},
    };
    for (const TransformStep &step : stage2)
      if (failed(applyTransformStep(moduleRef, step, schedules, func)))
        return failure();
  } else if (phase == CPU_PHASE_LOWERTOLLVM) {
    // Lower to LLVM phase. Run after whole-module bufferization.
    if (failed(applyTransformStep(
            moduleRef, {schedules.lowerToLLVMModule.get(), "lowerToLLVM"},
            schedules, func)))
      return failure();
  } else {
    return func.emitError("Invalid phase: ")
           << phase << " (must be CPU_PHASE_OPTIMIZE or CPU_PHASE_LOWERTOLLVM)";
  }

  LLVM_DEBUG(llvm::dbgs() << "Successfully lowered phase " << phase
                          << " for: " << funcName << "\n");
  return success();
}

/// Return true if the function signature contains non-TT float types
/// (e.g. f8E8M0FNU, f4E2M1FN) that are used for scaled GEMMs.
/// These types conflict with ConvertNarrowTypeSignatures / EmulateNarrowTypes
/// passes that run later in the pipeline, so we skip optimization for them.
static bool hasNonTTFloatArgs(func::FuncOp func) {
  auto check = [](Type t) {
    Type elem;
    if (auto shaped = dyn_cast<ShapedType>(t))
      elem = shaped.getElementType();
    else
      elem = t;
    return isa<FloatType>(elem) && !rock::isTTFloat(elem) &&
           (elem.getIntOrFloatBitWidth() == 8 ||
            elem.getIntOrFloatBitWidth() == 4);
  };
  for (Type argTy : func.getArgumentTypes())
    if (check(argTy))
      return true;
  for (Type resTy : func.getResultTypes())
    if (check(resTy))
      return true;
  return false;
}

void CpuLowerVerifierPass::runOnOperation() {
  ModuleOp module = getOperation();
  MLIRContext *ctx = &getContext();

  // Collect all functions with the cpu_verifier attribute
  // We collect them first because we'll be modifying the module
  SmallVector<func::FuncOp> cpuVerifierFuncs;
  module.walk([&](func::FuncOp func) {
    if (func->hasAttr(rock::CpuVerifierAttr::getMnemonic()))
      cpuVerifierFuncs.push_back(func);
  });

  if (cpuVerifierFuncs.empty()) {
    LLVM_DEBUG(llvm::dbgs() << "No CPU verifier functions found\n");
    return;
  }

  LLVM_DEBUG(llvm::dbgs() << "Found " << cpuVerifierFuncs.size()
                          << " CPU verifier function(s), running phase "
                          << phase << "\n");

  // Create all transform schedules
  auto maybeSchedules = createTransformSchedules(ctx);
  if (failed(maybeSchedules)) {
    return signalPassFailure();
  }
  TransformSchedules &schedules = maybeSchedules.value();

  // Lower each function in isolation using detach/reattach pattern
  // For each function, we detach all other operations, run transforms, then
  // reattach
  for (func::FuncOp func : cpuVerifierFuncs) {
    // TODO: CpuLowerVerifier doesn't work well with our passes to do
    // f4E2M1FN -> i4 -> packed i8 (ConvertNarrowTypeSignatures and
    // EmulateNarrowTypes). Skip scaled GEMM verifiers for now.
    if (hasNonTTFloatArgs(func)) {
      LLVM_DEBUG(llvm::dbgs()
                 << "Skipping " << func.getName()
                 << ": contains non-TT float types (scaled GEMM)\n");
      continue;
    }
    if (failed(lowerSingleFunction(func, schedules))) {
      return signalPassFailure();
    }
  }

  LLVM_DEBUG(llvm::dbgs() << "CPU verifier lowering completed\n");
}
