//===- LowerCpuVerifier.cpp - Lower CPU verifier functions ----------------===//
//
// Copyright 2026 Advanced Micro Devices.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// =============================================================================
//
// This pass lowers ONLY functions marked with "rock.cpu_verifier" attribute.
// These are CPU verification functions generated by rocmlir-gen.
//
// The pass uses the MLIR Transform Interpreter to apply transform sequences
// that tile, vectorize, and lower operations to LLVM. It runs in two phases:
// - Phase 1: tiling, vectorization, unroll (before whole-module bufferization)
// - Phase 2: lowerToLLVM (after whole-module bufferization)
//
// Functions are isolated using detach/reattach to run transforms on each
// verifier function independently.
//
//===----------------------------------------------------------------------===//

#include "Schedules.h"

#include "mlir/Conversion/CPU/Passes.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Bufferization/IR/Bufferization.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/Rock/IR/Rock.h"
#include "mlir/Dialect/Rock/utility/tritonUtils.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/Dialect/Transform/IR/TransformDialect.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/Pass/Pass.h"
#include "mlir/utils/DetachReattach.h"

#include "llvm/Support/Debug.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/raw_ostream.h"

namespace mlir {
namespace cpu {
#define GEN_PASS_DEF_CPULOWERVERIFIERPASS
#include "mlir/Conversion/CPU/Passes.h.inc"
} // namespace cpu
} // namespace mlir

#define DEBUG_TYPE "cpu-lower-verifier"

using namespace mlir;
using namespace mlir::cpu;

namespace {

struct CpuLowerVerifierPass
    : public cpu::impl::CpuLowerVerifierPassBase<CpuLowerVerifierPass> {
  using CpuLowerVerifierPassBase::CpuLowerVerifierPassBase;

  void getDependentDialects(DialectRegistry &registry) const override {
    // Call base class to include dialects from Passes.td
    CpuLowerVerifierPassBase::getDependentDialects(registry);

    // Register all transform dialect extensions needed for the schedules
    registerScheduleDialectExtensions(registry);
  }

  void runOnOperation() override;

private:
  /// Dump the IR and transform sequence to /tmp for debugging
  void dumpBeforeTransform(ModuleOp targetModule, ModuleOp transformModule,
                           StringRef funcName, StringRef phaseName);

  /// Lower a single CPU verifier function using the transform interpreter
  LogicalResult lowerSingleFunction(func::FuncOp func,
                                    const TransformSchedules &schedules);
};

} // end anonymous namespace

void CpuLowerVerifierPass::dumpBeforeTransform(ModuleOp targetModule,
                                               ModuleOp transformModule,
                                               StringRef funcName,
                                               StringRef phaseName) {
  // Only dump if dump-schedules-path option was specified
  if (dumpSchedulesPath.empty())
    return;

  // Use the path specified by the pass option
  std::string dumpDir = dumpSchedulesPath;
  std::error_code ec = llvm::sys::fs::create_directory(dumpDir);
  if (ec && ec != std::errc::file_exists) {
    LLVM_DEBUG(llvm::dbgs() << "Warning: Could not create dump directory "
                            << dumpDir << ": " << ec.message() << "\n");
    return;
  }

  // Create filename: cpu_dump/cpu_verifier_<funcname>_<phase>.mlir
  std::string filename =
      dumpDir + "/cpu_verifier_" + funcName.str() + "_" + phaseName.str() + ".mlir";

  llvm::raw_fd_ostream outFile(filename, ec, llvm::sys::fs::OF_Text);

  if (ec) {
    LLVM_DEBUG(llvm::dbgs() << "Warning: Could not open dump file " << filename
                            << ": " << ec.message() << "\n");
    return;
  }

  outFile << "// =============================================================\n";
  outFile << "// CPU Verifier Dump: " << funcName << " - " << phaseName << " phase\n";
  outFile << "// =============================================================\n\n";

  outFile << "// --- Target IR (before " << phaseName << ") ---\n";
  targetModule.print(outFile);
  outFile << "\n\n";

  outFile << "// --- Transform Sequence (" << phaseName << ") ---\n";
  transformModule.print(outFile);
  outFile << "\n";

  LLVM_DEBUG(llvm::dbgs() << "Dumped IR and transform to: " << filename << "\n");
}

/// Describes a single transform step in the lowering pipeline.
struct TransformStep {
  ModuleOp module;  // The transform module to apply
  StringRef name;   // Name of this step (e.g., "optimization", "vectorization")
};

LogicalResult
CpuLowerVerifierPass::lowerSingleFunction(func::FuncOp func,
                                          const TransformSchedules &schedules) {
  StringRef funcName = func.getName();
  ModuleOp module = func->getParentOfType<ModuleOp>();

  LLVM_DEBUG(llvm::dbgs() << "Lowering CPU verifier function: " << funcName
                          << "\n");

  // Step 1: Detach all functions except the target function.
  // Other module-level operations (globals, etc.) are left in place.
  // Stubs are created to keep symbol references valid during transformation.
  auto shouldDetach = [&](func::FuncOp f) { return f.getName() != funcName; };

  DetachedFuncs detached = detachFuncs(module, shouldDetach);
  LLVM_DEBUG(llvm::dbgs() << "  Detached " << detached.entries.size()
                          << " functions for isolation\n");

  // Step 2: Build the pipeline of main transform steps based on phase option
  SmallVector<TransformStep> pipeline;
  if (phase == CPU_PHASE_OPTIMIZE) {
    // Optimization phase: tiling, vectorization, unroll
    // Run before whole-module bufferization
    pipeline = {
        {schedules.tilingModule.get(), "tiling"},
        {schedules.vectorizationModule.get(), "vectorization"},
        {schedules.unrollModule.get(), "unroll"},
    };
  } else if (phase == CPU_PHASE_LOWERTOLLVM) {
    // Lower to LLVM phase
    // Run after whole-module bufferization
    pipeline = {
        {schedules.lowerToLLVMModule.get(), "lowerToLLVM"},
    };
  } else {
    reattachFuncs(module, detached);
    return func.emitError("Invalid phase: ")
           << phase << " (must be CPU_PHASE_OPTIMIZE or CPU_PHASE_LOWERTOLLVM)";
  }

  // We need to wrap the module in OwningOpRef for applyTransformSequence
  // but we don't own it, so we use a non-owning reference pattern
  OwningOpRef<ModuleOp> moduleRef(module);

  // Step 3: Apply each transform step with pre/post sequences
  for (const TransformStep &step : pipeline) {
    // 3.1. Pre-sequence
    std::string prePhaseName = "pre_" + step.name.str();
    LLVM_DEBUG(llvm::dbgs() << "    Applying " << prePhaseName << "...\n");
    dumpBeforeTransform(module, schedules.preModule.get(), funcName,
                        prePhaseName);
    if (failed(applyTransformSequence(moduleRef, schedules.preModule.get(),
                                      "pre", funcName))) {
      reattachFuncs(module, detached);
      return func.emitError("Pre transform failed before ") << step.name;
    }

    // 3.2. Main transform
    LLVM_DEBUG(llvm::dbgs() << "    Applying " << step.name << "...\n");
    dumpBeforeTransform(module, step.module, funcName, step.name);
    if (failed(applyTransformSequence(moduleRef, step.module, step.name,
                                      funcName))) {
      reattachFuncs(module, detached);
      return func.emitError("Transform failed at ") << step.name;
    }

    // 3.3. Post-sequence
    std::string postPhaseName = "post_" + step.name.str();
    LLVM_DEBUG(llvm::dbgs() << "    Applying " << postPhaseName << "...\n");
    dumpBeforeTransform(module, schedules.postModule.get(), funcName,
                        postPhaseName);
    if (failed(applyTransformSequence(moduleRef, schedules.postModule.get(),
                                      "post", funcName))) {
      reattachFuncs(module, detached);
      return func.emitError("Post transform failed after ") << step.name;
    }
  }

  // Release the non-owning reference (don't delete the module!)
  (void)moduleRef.release();

  // Step 4: Reattach the detached operations
  reattachFuncs(module, detached);

  LLVM_DEBUG(llvm::dbgs() << "Successfully lowered phase " << phase
                          << " for: " << funcName << "\n");
  return success();
}

/// Return true if the function signature contains non-TT float types
/// (e.g. f8E8M0FNU, f4E2M1FN) that are used for scaled GEMMs.
/// These types conflict with ConvertNarrowTypeSignatures / EmulateNarrowTypes
/// passes that run later in the pipeline, so we skip optimization for them.
static bool hasNonTTFloatArgs(func::FuncOp func) {
  auto check = [](Type t) {
    Type elem;
    if (auto shaped = dyn_cast<ShapedType>(t))
      elem = shaped.getElementType();
    else
      elem = t;
    return isa<FloatType>(elem) && !rock::isTTFloat(elem) &&
           (elem.getIntOrFloatBitWidth() == 8 ||
            elem.getIntOrFloatBitWidth() == 4);
  };
  for (Type argTy : func.getArgumentTypes())
    if (check(argTy))
      return true;
  for (Type resTy : func.getResultTypes())
    if (check(resTy))
      return true;
  return false;
}

void CpuLowerVerifierPass::runOnOperation() {
  ModuleOp module = getOperation();
  MLIRContext *ctx = &getContext();

  // Collect all functions with the cpu_verifier attribute
  // We collect them first because we'll be modifying the module
  SmallVector<func::FuncOp> cpuVerifierFuncs;
  module.walk([&](func::FuncOp func) {
    if (func->hasAttr(rock::CpuVerifierAttr::getMnemonic()))
      cpuVerifierFuncs.push_back(func);
  });

  if (cpuVerifierFuncs.empty()) {
    LLVM_DEBUG(llvm::dbgs() << "No CPU verifier functions found\n");
    return;
  }

  LLVM_DEBUG(llvm::dbgs() << "Found " << cpuVerifierFuncs.size()
                          << " CPU verifier function(s), running phase "
                          << phase << "\n");

  // Create all transform schedules
  auto maybeSchedules = createTransformSchedules(ctx);
  if (failed(maybeSchedules)) {
    return signalPassFailure();
  }
  TransformSchedules &schedules = maybeSchedules.value();

  // Lower each function in isolation using detach/reattach pattern
  // For each function, we detach all other operations, run transforms, then reattach
  for (func::FuncOp func : cpuVerifierFuncs) {
    // TODO: CpuLowerVerifier doesn't work well with our passes to do
    // f4E2M1FN -> i4 -> packed i8 (ConvertNarrowTypeSignatures and
    // EmulateNarrowTypes). Skip scaled GEMM verifiers for now.
    if (hasNonTTFloatArgs(func)) {
      LLVM_DEBUG(llvm::dbgs()
                 << "Skipping " << func.getName()
                 << ": contains non-TT float types (scaled GEMM)\n");
      continue;
    }
    if (failed(lowerSingleFunction(func, schedules))) {
      return signalPassFailure();
    }
  }

  LLVM_DEBUG(llvm::dbgs() << "CPU verifier lowering completed\n");
}
