//===- LowerCpuVerifier.cpp - Lower CPU verifier functions ----------------===//
//
// Copyright 2026 Advanced Micro Devices.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// =============================================================================
//
// This pass lowers ONLY functions marked with "rock.cpu_verifier" attribute.
// These are CPU verification functions generated by rocmlir-gen that use
// tensor semantics and need to be bufferized before general host lowering.
//
// The pass uses the MLIR Transform Interpreter to apply a transform sequence
// that bufferizes and lowers the tensor operations to loops.
//
//===----------------------------------------------------------------------===//

#include "Schedules.h"

#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Bufferization/IR/Bufferization.h"
#include "mlir/Dialect/CPU/Passes.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/Dialect/Transform/IR/TransformDialect.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/IRMapping.h"
#include "mlir/IR/SymbolTable.h"
#include "mlir/Pass/Pass.h"

#include "llvm/Support/Debug.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/raw_ostream.h"

namespace mlir {
namespace cpu {
#define GEN_PASS_DEF_CPULOWERVERIFIERPASS
#include "mlir/Dialect/CPU/Passes.h.inc"
} // namespace cpu
} // namespace mlir

#define DEBUG_TYPE "cpu-lower-verifier"

using namespace mlir;
using namespace mlir::cpu;

namespace {

/// Check if a function has the cpu_verifier attribute
static bool isCpuVerifierFunc(func::FuncOp func) {
  return func->hasAttr("rock.cpu_verifier");
}

struct CpuLowerVerifierPass
    : public cpu::impl::CpuLowerVerifierPassBase<CpuLowerVerifierPass> {
  using CpuLowerVerifierPassBase::CpuLowerVerifierPassBase;

  void getDependentDialects(DialectRegistry &registry) const override {
    // Call base class to include dialects from Passes.td
    CpuLowerVerifierPassBase::getDependentDialects(registry);

    // Register all transform dialect extensions needed for the schedules
    registerScheduleDialectExtensions(registry);
  }

  void runOnOperation() override;

private:
  /// Dump the IR and transform sequence to /tmp for debugging
  void dumpBeforeTransform(ModuleOp targetModule, ModuleOp transformModule,
                           StringRef funcName, StringRef phaseName);

  /// Lower a single CPU verifier function using the transform interpreter
  LogicalResult lowerSingleFunction(func::FuncOp func,
                                    const TransformSchedules &schedules);

  /// Update call sites in the module to use memref arguments instead of tensors
  /// after the function has been bufferized with bufferize_function_boundaries=true
  void updateCallSites(ModuleOp module, StringRef funcName);

  /// Unwrap nested module structure if present
  /// Some transforms may wrap their result in an additional module, which would
  /// cause subsequent transforms like one_shot_bufferize to not process the
  /// inner function
  void unwrapNestedModule(OwningOpRef<ModuleOp> &module, StringRef funcName);
};

} // end anonymous namespace

void CpuLowerVerifierPass::dumpBeforeTransform(ModuleOp targetModule,
                                               ModuleOp transformModule,
                                               StringRef funcName,
                                               StringRef phaseName) {
  // Create filename: /tmp/cpu_verifier_<funcname>_<phase>.mlir
  std::string filename =
      "/tmp/cpu_verifier_" + funcName.str() + "_" + phaseName.str() + ".mlir";

  std::error_code ec;
  llvm::raw_fd_ostream outFile(filename, ec, llvm::sys::fs::OF_Text);

  if (ec) {
    LLVM_DEBUG(llvm::dbgs() << "Warning: Could not open dump file " << filename
                            << ": " << ec.message() << "\n");
    return;
  }

  outFile << "// =============================================================\n";
  outFile << "// CPU Verifier Dump: " << funcName << " - " << phaseName << " phase\n";
  outFile << "// =============================================================\n\n";

  outFile << "// --- Target IR (before " << phaseName << ") ---\n";
  targetModule.print(outFile);
  outFile << "\n\n";

  outFile << "// --- Transform Sequence (" << phaseName << ") ---\n";
  transformModule.print(outFile);
  outFile << "\n";

  LLVM_DEBUG(llvm::dbgs() << "Dumped IR and transform to: " << filename << "\n");
}

void CpuLowerVerifierPass::unwrapNestedModule(OwningOpRef<ModuleOp> &module,
                                              StringRef funcName) {
  // Check if there's a nested module inside the outer module
  // This can happen when some transforms wrap their result in a new module
  ModuleOp nestedModule = nullptr;
  for (Operation &op : module->getBody()->getOperations()) {
    if (auto nested = dyn_cast<ModuleOp>(&op)) {
      nestedModule = nested;
      break;
    }
  }

  if (!nestedModule) {
    return; // No nested module, nothing to do
  }

  LLVM_DEBUG(llvm::dbgs() << "  Unwrapping nested module structure\n");

  // Find the function inside the nested module
  func::FuncOp funcOp = nullptr;
  nestedModule.walk([&](func::FuncOp f) {
    if (f.getName() == funcName)
      funcOp = f;
  });

  if (!funcOp) {
    // Function not found in nested module, leave as-is
    return;
  }

  // Create a new clean module with just the function
  MLIRContext *ctx = module->getContext();
  Location loc = module->getLoc();
  OwningOpRef<ModuleOp> newModule = ModuleOp::create(loc);

  // Clone the function into the new module
  OpBuilder builder(ctx);
  builder.setInsertionPointToStart(newModule->getBody());
  builder.clone(*funcOp.getOperation());

  // Replace the old module with the new one
  module = std::move(newModule);
}

void CpuLowerVerifierPass::updateCallSites(ModuleOp module,
                                           StringRef funcName) {
  // Find the lowered function to get its signature
  auto loweredFunc = module.lookupSymbol<func::FuncOp>(funcName);
  if (!loweredFunc) {
    LLVM_DEBUG(llvm::dbgs() << "  Could not find lowered function " << funcName
                            << "\n");
    return;
  }

  // Find all call ops that call the target function
  SmallVector<func::CallOp> callsToUpdate;
  module.walk([&](func::CallOp callOp) {
    if (callOp.getCallee() == funcName)
      callsToUpdate.push_back(callOp);
  });

  if (callsToUpdate.empty()) {
    LLVM_DEBUG(llvm::dbgs() << "  No call sites found for " << funcName << "\n");
    return;
  }

  LLVM_DEBUG(llvm::dbgs() << "  Updating " << callsToUpdate.size()
                          << " call site(s) for " << funcName << "\n");

  for (func::CallOp callOp : callsToUpdate) {
    OpBuilder builder(callOp);
    Location loc = callOp.getLoc();

    // Collect the source memrefs from the to_tensor operands
    SmallVector<Value> memrefArgs;
    SmallVector<bufferization::ToTensorOp> toTensorOps;

    for (Value operand : callOp.getOperands()) {
      auto toTensorOp = operand.getDefiningOp<bufferization::ToTensorOp>();
      if (toTensorOp) {
        memrefArgs.push_back(toTensorOp.getOperand());
        toTensorOps.push_back(toTensorOp);
      } else {
        // If the operand is not from a to_tensor, it might already be a memref
        // or something else - this shouldn't happen in our expected pattern
        LLVM_DEBUG(llvm::dbgs()
                   << "  Warning: operand is not from to_tensor: " << operand
                   << "\n");
        memrefArgs.push_back(operand);
      }
    }

    // Create a new call with the lowered function's return types
    // With bufferize_function_boundaries=true, the function signature changes
    // from (tensor, tensor, tensor) -> tensor to (memref, memref, memref) -> memref
    auto newCall = builder.create<func::CallOp>(
        loc, funcName, loweredFunc.getResultTypes(), memrefArgs);

    // Find and remove the to_buffer and copy ops that use the old result
    // The new call returns a memref directly, so we don't need to_buffer anymore
    if (!callOp.getResults().empty()) {
      Value oldResult = callOp.getResult(0);
      for (Operation *user : llvm::make_early_inc_range(oldResult.getUsers())) {
        if (auto toBufferOp = dyn_cast<bufferization::ToBufferOp>(user)) {
          // Replace uses of to_buffer result with the new call's result
          // (if the function returns a memref)
          if (!newCall.getResults().empty()) {
            toBufferOp.getResult().replaceAllUsesWith(newCall.getResult(0));
          }
          // Find and remove the copy that uses the to_buffer result
          Value buffer = toBufferOp.getResult();
          for (Operation *bufUser :
               llvm::make_early_inc_range(buffer.getUsers())) {
            if (auto copyOp = dyn_cast<memref::CopyOp>(bufUser)) {
              copyOp.erase();
            }
          }
          toBufferOp.erase();
        }
      }
    }

    // Erase the old call
    callOp.erase();

    // Erase the to_tensor ops if they have no other uses
    for (auto toTensorOp : toTensorOps) {
      if (toTensorOp.use_empty())
        toTensorOp.erase();
    }
  }
}

LogicalResult
CpuLowerVerifierPass::lowerSingleFunction(func::FuncOp func,
                                          const TransformSchedules &schedules) {
  MLIRContext *ctx = &getContext();
  Location loc = func.getLoc();
  StringRef funcName = func.getName();

  LLVM_DEBUG(llvm::dbgs() << "Lowering CPU verifier function: " << funcName
                          << "\n");

  // Step 1: Create a temporary module containing only this function
  OwningOpRef<ModuleOp> tempModule = ModuleOp::create(loc);

  // Step 2: Clone the function into the temporary module
  IRMapping mapping;
  Operation *clonedOp = func->clone(mapping);
  auto clonedFunc = cast<func::FuncOp>(clonedOp);
  tempModule->push_back(clonedFunc);

  // ===== Phase 1: Pre → Optimization → Post =====
  LLVM_DEBUG(llvm::dbgs() << "  Phase 1: Optimization\n");

  // Pre-sequence (canonicalize + cse)
  LLVM_DEBUG(llvm::dbgs() << "    Applying pre sequence...\n");
  dumpBeforeTransform(tempModule.get(), schedules.preModule.get(), funcName,
                      "pre_optimization");
  if (failed(applyTransformSequence(tempModule.get(), schedules.preModule.get(),
                                    "pre"))) {
    return func.emitError("Pre transform failed before optimization");
  }

  // Optimization sequence (tiling)
  LLVM_DEBUG(llvm::dbgs() << "    Applying optimization sequence...\n");
  dumpBeforeTransform(tempModule.get(), schedules.optimizationModule.get(),
                      funcName, "optimization");
  if (failed(applyTransformSequence(tempModule.get(),
                                    schedules.optimizationModule.get(),
                                    "optimization"))) {
    return func.emitError("Optimization transform failed for function");
  }

  // Unwrap any nested module structure created by the transform
  unwrapNestedModule(tempModule, funcName);

  // Post-sequence (tiling canonicalization + LICM + hoisting)
  LLVM_DEBUG(llvm::dbgs() << "    Applying post sequence...\n");
  dumpBeforeTransform(tempModule.get(), schedules.postModule.get(), funcName,
                      "post_optimization");
  if (failed(applyTransformSequence(tempModule.get(),
                                    schedules.postModule.get(), "post"))) {
    return func.emitError("Post transform failed after optimization");
  }

  // ===== Phase 2: Pre → Vectorization → Post =====
  LLVM_DEBUG(llvm::dbgs() << "  Phase 2: Vectorization\n");

  // Pre-sequence
  LLVM_DEBUG(llvm::dbgs() << "    Applying pre sequence...\n");
  dumpBeforeTransform(tempModule.get(), schedules.preModule.get(), funcName,
                      "pre_vectorization");
  if (failed(applyTransformSequence(tempModule.get(), schedules.preModule.get(),
                                    "pre"))) {
    return func.emitError("Pre transform failed before vectorization");
  }

  // Vectorization sequence
  LLVM_DEBUG(llvm::dbgs() << "    Applying vectorization sequence...\n");
  dumpBeforeTransform(tempModule.get(), schedules.vectorizationModule.get(),
                      funcName, "vectorization");
  if (failed(applyTransformSequence(tempModule.get(),
                                    schedules.vectorizationModule.get(),
                                    "vectorization"))) {
    return func.emitError("Vectorization transform failed for function");
  }

  // Unwrap any nested module structure
  unwrapNestedModule(tempModule, funcName);

  // Post-sequence
  LLVM_DEBUG(llvm::dbgs() << "    Applying post sequence...\n");
  dumpBeforeTransform(tempModule.get(), schedules.postModule.get(), funcName,
                      "post_vectorization");
  if (failed(applyTransformSequence(tempModule.get(),
                                    schedules.postModule.get(), "post"))) {
    return func.emitError("Post transform failed after vectorization");
  }

  // ===== Phase 3: Pre → Lowering → Post =====
  LLVM_DEBUG(llvm::dbgs() << "  Phase 3: Lowering\n");

  // Pre-sequence
  LLVM_DEBUG(llvm::dbgs() << "    Applying pre sequence...\n");
  dumpBeforeTransform(tempModule.get(), schedules.preModule.get(), funcName,
                      "pre_lowering");
  if (failed(applyTransformSequence(tempModule.get(), schedules.preModule.get(),
                                    "pre"))) {
    return func.emitError("Pre transform failed before lowering");
  }

  // Lowering sequence (bufferization + LLVM lowering)
  LLVM_DEBUG(llvm::dbgs() << "    Applying lowering sequence...\n");
  dumpBeforeTransform(tempModule.get(), schedules.loweringModule.get(),
                      funcName, "lowering");
  if (failed(applyTransformSequence(tempModule.get(),
                                    schedules.loweringModule.get(),
                                    "lowering"))) {
    return func.emitError("Lowering transform failed for function");
  }

  // Post-sequence after lowering
  LLVM_DEBUG(llvm::dbgs() << "    Applying post sequence...\n");
  dumpBeforeTransform(tempModule.get(), schedules.postModule.get(), funcName,
                      "post_lowering");
  if (failed(applyTransformSequence(tempModule.get(),
                                    schedules.postModule.get(), "post"))) {
    return func.emitError("Post transform failed after lowering");
  }

  // Step 5: Get the lowered function from the temporary module
  // After lowering to LLVM, the function is now LLVM::LLVMFuncOp
  func::FuncOp loweredFunc = nullptr;
  tempModule->walk([&](func::FuncOp f) { loweredFunc = f; });

  if (!loweredFunc) {
    return func.emitError("Could not find lowered function in temporary module");
  }

  // Step 6: Replace the original function with the lowered one
  ModuleOp parentModule = func->getParentOfType<ModuleOp>();
  OpBuilder builder(ctx);
  builder.setInsertionPointToStart(parentModule.getBody());

  // Copy all top-level operations from tempModule to parentModule
  // (globals, function declarations, etc.) using SymbolOpInterface for genericity
  for (Operation &op : tempModule->getBody()->getOperations()) {
    // Skip module terminator
    if (op.hasTrait<OpTrait::IsTerminator>())
      continue;

    // Check if this is a symbol-defining operation
    if (auto symbolOp = dyn_cast<SymbolOpInterface>(&op)) {
      StringRef symName = symbolOp.getName();

      // Skip the lowered function itself (we handle it separately below)
      if (symName == funcName)
        continue;

      // Check if symbol already exists in parent module
      Operation *existing = parentModule.lookupSymbol(symName);
      if (existing) {
        // Special case: replace func.func with llvm.func (LLVM version is preferred)
        if (isa<func::FuncOp>(existing) && isa<LLVM::LLVMFuncOp>(&op)) {
          existing->erase();
        } else {
          // Symbol already exists, skip to avoid duplicates
          continue;
        }
      }

      builder.clone(op);
      LLVM_DEBUG(llvm::dbgs() << "  Copied symbol: " << symName << "\n");
    }
  }

  // Clone the lowered function back to the original module
  builder.setInsertionPoint(func);
  IRMapping backMapping;
  Operation *finalOp = loweredFunc->clone(backMapping);
  builder.insert(finalOp);

  // Erase the original function
  func.erase();

  // Step 7: Update call sites to use memref arguments instead of tensors
  // This is needed because bufferize_function_boundaries=true changes the
  // function signature from tensors to memrefs
  updateCallSites(parentModule, funcName);

  LLVM_DEBUG(llvm::dbgs() << "Successfully lowered: " << funcName << "\n");
  return success();
}

void CpuLowerVerifierPass::runOnOperation() {
  ModuleOp module = getOperation();
  MLIRContext *ctx = &getContext();

  // Collect all functions with the cpu_verifier attribute
  // We collect them first because we'll be modifying the module
  SmallVector<func::FuncOp> cpuVerifierFuncs;
  module.walk([&](func::FuncOp func) {
    if (isCpuVerifierFunc(func))
      cpuVerifierFuncs.push_back(func);
  });

  if (cpuVerifierFuncs.empty()) {
    LLVM_DEBUG(llvm::dbgs() << "No CPU verifier functions found\n");
    return;
  }

  LLVM_DEBUG(llvm::dbgs() << "Found " << cpuVerifierFuncs.size()
                          << " CPU verifier function(s)\n");

  // Create all transform schedules
  auto schedulesOrErr = createTransformSchedules(ctx);
  if (failed(schedulesOrErr)) {
    return signalPassFailure();
  }
  TransformSchedules &schedules = *schedulesOrErr;

  // Lower each function in isolation using the transform interpreter
  // Pipeline: Pre → Optimization → Post → Pre → Vectorization → Post → Pre → Lowering → Post
  for (func::FuncOp func : cpuVerifierFuncs) {
    if (failed(lowerSingleFunction(func, schedules))) {
      return signalPassFailure();
    }
  }

  // Ensure memrefCopy declaration exists if any llvm.call @memrefCopy was generated
  // The MemRefToLLVM conversion generates calls to memrefCopy but doesn't create
  // the declaration automatically
  bool hasMemrefCopyCall = false;
  module.walk([&](LLVM::CallOp callOp) {
    if (callOp.getCallee() && *callOp.getCallee() == "memrefCopy")
      hasMemrefCopyCall = true;
  });

  if (hasMemrefCopyCall && !module.lookupSymbol<LLVM::LLVMFuncOp>("memrefCopy")) {
    OpBuilder builder(ctx);
    builder.setInsertionPointToStart(module.getBody());

    // memrefCopy signature: void memrefCopy(i64 elemSize, ptr src, ptr dst)
    auto ptrType = LLVM::LLVMPointerType::get(ctx);
    auto i64Type = IntegerType::get(ctx, 64);
    auto voidType = LLVM::LLVMVoidType::get(ctx);
    auto funcType = LLVM::LLVMFunctionType::get(voidType, {i64Type, ptrType, ptrType});

    builder.create<LLVM::LLVMFuncOp>(module.getLoc(), "memrefCopy", funcType,
                                     LLVM::Linkage::External);
    LLVM_DEBUG(llvm::dbgs() << "Created memrefCopy declaration\n");
  }

  LLVM_DEBUG(llvm::dbgs() << "CPU verifier lowering completed\n");
}
