//===- LowerCpuVerifier.cpp - Lower CPU verifier functions ----------------===//
//
// Copyright 2026 Advanced Micro Devices.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// =============================================================================
//
// This pass lowers ONLY functions marked with "rock.cpu_verifier" attribute.
// These are CPU verification functions generated by rocmlir-gen that use
// tensor semantics and need to be bufferized before general host lowering.
//
// The pass uses the MLIR Transform Interpreter to apply a transform sequence
// that bufferizes and lowers the tensor operations to loops.
//
//===----------------------------------------------------------------------===//

#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Bufferization/IR/Bufferization.h"
#include "mlir/Dialect/Bufferization/TransformOps/BufferizationTransformOps.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/Func/TransformOps/FuncTransformOps.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/Linalg/TransformOps/DialectExtension.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/MemRef/TransformOps/MemRefTransformOps.h"
#include "mlir/Dialect/MemRef/Transforms/AllocationOpInterfaceImpl.h"
#include "mlir/Dialect/CPU/Passes.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/Dialect/Affine/IR/ValueBoundsOpInterfaceImpl.h"
#include "mlir/Dialect/Arith/IR/ValueBoundsOpInterfaceImpl.h"
#include "mlir/Dialect/SCF/IR/ValueBoundsOpInterfaceImpl.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/Dialect/Tensor/IR/ValueBoundsOpInterfaceImpl.h"
#include "mlir/Dialect/Transform/IR/TransformDialect.h"
#include "mlir/Dialect/Vector/Transforms/BufferizableOpInterfaceImpl.h"
#include "mlir/Dialect/Vector/Transforms/SubsetOpInterfaceImpl.h"
#include "mlir/Dialect/Vector/TransformOps/VectorTransformOps.h"
#include "mlir/Dialect/Transform/IR/TransformOps.h"
#include "mlir/Dialect/Transform/Interfaces/TransformInterfaces.h"
#include "mlir/Dialect/Transform/Transforms/TransformInterpreterUtils.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/DialectRegistry.h"
#include "mlir/IR/IRMapping.h"
#include "mlir/IR/SymbolTable.h"
#include "mlir/Parser/Parser.h"
#include "mlir/Pass/Pass.h"

#include "llvm/Support/Debug.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/raw_ostream.h"

namespace mlir {
namespace cpu {
#define GEN_PASS_DEF_CPULOWERVERIFIERPASS
#include "mlir/Dialect/CPU/Passes.h.inc"
} // namespace cpu
} // namespace mlir

#define DEBUG_TYPE "cpu-lower-verifier"

using namespace mlir;
using namespace mlir::cpu;

namespace {

constexpr const char *kPreSequence = R"mlir(
module attributes {transform.with_named_sequence} {
  transform.named_sequence @__transform_main(%arg0: !transform.any_op {transform.consumed}) {
    %1 = transform.structured.match ops{["func.func"]} in %arg0 : (!transform.any_op) -> !transform.any_op
    %2 = transform.apply_registered_pass "canonicalize" to %1 : (!transform.any_op) -> !transform.any_op
    transform.apply_cse to %2 : !transform.any_op
    transform.yield 
  }
}
)mlir";  

constexpr const char *kPostSequence = R"mlir(
module attributes {transform.with_named_sequence} {
  transform.named_sequence @__transform_main(%arg0: !transform.any_op {transform.consumed}) {
    %1 = transform.structured.match ops{["func.func"]} in %arg0 : (!transform.any_op) -> !transform.any_op
    %2 = transform.structured.match interface{LoopLikeInterface} in %1 : (!transform.any_op) -> !transform.any_op
    transform.apply_licm to %2 : !transform.any_op
    
    %func = transform.structured.match ops{["func.func"]} in %1 : (!transform.any_op) -> !transform.any_op
    %3 = transform.structured.hoist_redundant_vector_transfers %func : (!transform.any_op) -> !transform.any_op
    %4 = transform.structured.hoist_redundant_vector_broadcasts %3 : (!transform.any_op) -> !transform.any_op
    %5 = transform.apply_registered_pass "canonicalize" to %4 : (!transform.any_op) -> !transform.any_op
    transform.yield 
  }
}
)mlir";  

/// Transform sequence for optimization (tiling) of CPU verifier functions.
/// This sequence tiles the matmul and applies canonicalization.
/// It ends before bufferization.
constexpr const char *kOptimizationSequence = R"mlir(
module attributes {transform.with_named_sequence} {
  transform.named_sequence @__transform_main(%arg0: !transform.any_op {transform.consumed}) {
    // TODO: Get rid of unit dims (for batch mamtul)
    %0 = transform.structured.match attributes {rock.matmul} in %arg0 : (!transform.any_op) -> !transform.any_op

    %transformed, %loops:3 = transform.structured.fuse %0 tile_sizes [1, 256, 64] : (!transform.any_op) -> (!transform.any_op, !transform.any_op, !transform.any_op, !transform.any_op)
    %xxx, %loop = transform.structured.tile_using_for %transformed tile_sizes [0, 0, 0, 64] : (!transform.any_op) -> (!transform.any_op, !transform.any_op)

    %microkernel, %microkernel_loops:3 = transform.structured.tile_using_for %xxx tile_sizes [0, 8, 8, 1] : (!transform.any_op) -> (!transform.any_op, !transform.any_op, !transform.any_op, !transform.any_op)

    // TODO: We will probably need padding and/or packing here.

    %1 = transform.structured.match ops{["func.func"]} in %arg0 : (!transform.any_op) -> !transform.any_op
    %2 = transform.apply_registered_pass "canonicalize" to %1 : (!transform.any_op) -> !transform.any_op
    %3 = transform.apply_registered_pass "lower-affine" to %2 : (!transform.any_op) -> !transform.any_op
    transform.yield 
  }
}
)mlir";

constexpr const char *kVectorizationSequence = R"mlir(
module attributes {transform.with_named_sequence} {
  transform.named_sequence @__transform_main(%arg0: !transform.any_op {transform.consumed}) {
    %0 = transform.structured.match attributes {rock.matmul} in %arg0 : (!transform.any_op) -> !transform.any_op
    %1 = transform.get_parent_op %0 {isolated_from_above} : (!transform.any_op) -> !transform.any_op
    %2 = transform.structured.vectorize_children_and_apply_patterns %1 {vectorize_nd_extract, vectorize_padding} : (!transform.any_op) -> !transform.any_op
    transform.yield
  }
}
)mlir";

/// Transform sequence for lowering CPU verifier functions to LLVM.
/// This sequence starts with bufferization and lowers to LLVM dialect.
constexpr const char *kLoweringSequence = R"mlir(
module attributes {transform.with_named_sequence} {
  transform.named_sequence @__transform_main(%arg0: !transform.any_op {transform.consumed}) {

    %10 = transform.bufferization.one_shot_bufferize layout{IdentityLayoutMap} %arg0 {bufferize_function_boundaries = true} : (!transform.any_op) -> !transform.any_op

    // Lowering to LLVM

    %func = transform.structured.match ops{["func.func"]} in %10 : (!transform.any_op) -> !transform.any_op
    // Bufferization is quite dumb, so it will probably insert unnecesary memref copies.
    // We use CSE + canonicalize to remove them.
    %3 = transform.apply_registered_pass "cse" to %func : (!transform.any_op) -> !transform.any_op
    %4 = transform.apply_registered_pass "canonicalize" to %3 : (!transform.any_op) -> !transform.any_op

    // Add these after bufferization to hoist allocations out of loops
    %b10 = transform.apply_registered_pass "buffer-hoisting" to %4 : (!transform.any_op) -> !transform.any_op
    %c10 = transform.apply_registered_pass "buffer-loop-hoisting" to %b10 : (!transform.any_op) -> !transform.any_op
    // %d10 = transform.apply_registered_pass "buffer-deallocation" to %c10 : (!transform.any_op) -> !transform.any_op


    // Now time to lower vectors.
    %fff = transform.structured.match ops{["func.func"]} in %c10 : (!transform.any_op) -> !transform.any_op

    // TODO: group these lower-level controls into various properly named vector
    // lowering TD macros.
    transform.apply_patterns to %fff {
      transform.apply_patterns.vector.lower_contraction lowering_strategy = "outerproduct"
      transform.apply_patterns.vector.lower_outerproduct
      transform.apply_patterns.vector.transfer_permutation_patterns
      // transform.apply_patterns.vector.reorder_and_expand_multi_reduction_dims lowering_strategy = "innerparallel"
      // transform.apply_patterns.vector.multi_reduction_flattening lowering_strategy = "innerparallel"
      // transform.apply_patterns.vector.multi_reduction_unrolling lowering_strategy = "innerparallel"
      transform.apply_patterns.vector.split_transfer_full_partial split_transfer_strategy = "linalg-copy"
      transform.apply_patterns.vector.transfer_to_scf max_transfer_rank = 4 full_unroll = true
      transform.apply_patterns.vector.lower_transfer max_transfer_rank = 1
      transform.apply_patterns.vector.lower_shape_cast
      transform.apply_patterns.vector.lower_transpose lowering_strategy = "shuffle_1d"
    } : !transform.any_op

    // Now time to lower to LLVM
    %f = transform.apply_registered_pass "convert-vector-to-scf" to %fff : (!transform.any_op) -> !transform.any_op
    %f2 = transform.apply_registered_pass "convert-linalg-to-loops" to %f : (!transform.any_op) -> !transform.any_op

    // IMPORTANT: convert-vector-to-scf creates new allocations for vector transfers.
    // We must run buffer-loop-hoisting again to move these out of loops,
    // otherwise we get stack overflow from allocas inside loops.
    %fh1 = transform.apply_registered_pass "buffer-loop-hoisting" to %f2 : (!transform.any_op) -> !transform.any_op
    %fh2 = transform.apply_registered_pass "promote-buffers-to-stack" to %fh1 : (!transform.any_op) -> !transform.any_op

    %f3 = transform.apply_registered_pass "convert-scf-to-cf" to %fh2 : (!transform.any_op) -> !transform.any_op
    %f4 = transform.apply_registered_pass "expand-strided-metadata" to %f3 : (!transform.any_op) -> !transform.any_op
    %f5 = transform.apply_registered_pass "lower-affine" to %f4 : (!transform.any_op) -> !transform.any_op
    %f5b = transform.apply_registered_pass "convert-vector-to-llvm" with options = {"reassociate-fp-reductions" = false} to %f5 : (!transform.any_op) -> !transform.any_op

    transform.apply_conversion_patterns to %f5b {
      transform.apply_conversion_patterns.dialect_to_llvm "math"
      transform.apply_conversion_patterns.vector.vector_to_llvm
      transform.apply_conversion_patterns.dialect_to_llvm "memref"
      // transform.apply_conversion_patterns.func.func_to_llvm
      transform.apply_conversion_patterns.dialect_to_llvm "index"
      transform.apply_conversion_patterns.dialect_to_llvm "arith"
      transform.apply_conversion_patterns.dialect_to_llvm "cf"
    } with type_converter {
      transform.apply_conversion_patterns.memref.memref_to_llvm_type_converter
        {index_bitwidth = 64,
        use_bare_ptr = false,
        use_bare_ptr_memref_call_conv = false,
        use_opaque_pointers = true}
    } {
      legal_dialects = ["llvm"],
      partial_conversion
    } : !transform.any_op

    // Need to rematch here because:
    //   1. applying reconcile-unrealized-casts on the whole module yields the
    //      transform applies to transform, when called from a named sequence, at
    //      this time.
    //   2. apply_conversion patterns consumes the func but does not produce
    //      a new llvm.func.
    %f6 = transform.structured.match ops{["llvm.func"]} in %10
      : (!transform.any_op) -> !transform.any_op
    %f7 = transform.apply_registered_pass "reconcile-unrealized-casts" to %f6
      : (!transform.any_op) -> !transform.any_op

    transform.yield
  }
}
)mlir";

/// Check if a function has the cpu_verifier attribute
static bool isCpuVerifierFunc(func::FuncOp func) {
  return func->hasAttr("rock.cpu_verifier");
}

struct CpuLowerVerifierPass
    : public cpu::impl::CpuLowerVerifierPassBase<CpuLowerVerifierPass> {
  using CpuLowerVerifierPassBase::CpuLowerVerifierPassBase;

  void getDependentDialects(DialectRegistry &registry) const override {
    // Call base class to include dialects from Passes.td
    CpuLowerVerifierPassBase::getDependentDialects(registry);

    // Register transform dialect extensions needed for parsing the transform
    // sequence. This must be done here (not in runOnOperation) to avoid
    // thread-safety issues. The extensions provide ops like
    // transform.structured.match, transform.bufferization.one_shot_bufferize.
    linalg::registerTransformDialectExtension(registry);
    bufferization::registerTransformDialectExtension(registry);
    vector::registerTransformDialectExtension(registry);
    func::registerTransformDialectExtension(registry);
    memref::registerTransformDialectExtension(registry);

    // Register ValueBoundsOpInterface for dialects, required by
    // transform.structured.tile_using_for and other tiling transforms
    affine::registerValueBoundsOpInterfaceExternalModels(registry);
    arith::registerValueBoundsOpInterfaceExternalModels(registry);
    scf::registerValueBoundsOpInterfaceExternalModels(registry);
    tensor::registerValueBoundsOpInterfaceExternalModels(registry);

    // Register BufferizableOpInterface and SubsetOpInterface for vector dialect,
    // required by one_shot_bufferize when vector ops are present
    vector::registerBufferizableOpInterfaceExternalModels(registry);
    vector::registerSubsetOpInterfaceExternalModels(registry);

    // Register AllocationOpInterface for memref dialect,
    // required by buffer-hoisting and buffer-loop-hoisting passes
    memref::registerAllocationOpInterfaceExternalModels(registry);
  }

  void runOnOperation() override;

private:
  /// Dump the IR and transform sequence to /tmp for debugging
  void dumpBeforeTransform(ModuleOp targetModule, ModuleOp transformModule,
                           StringRef funcName, StringRef phaseName);

  /// Apply a single transform sequence to the temporary module
  LogicalResult applyTransformSequence(ModuleOp tempModule,
                                       ModuleOp transformModule,
                                       StringRef sequenceName);

  /// Lower a single CPU verifier function using the transform interpreter
  LogicalResult lowerSingleFunction(func::FuncOp func,
                                    ModuleOp preModule,
                                    ModuleOp optimizationModule,
                                    ModuleOp postModule,
                                    ModuleOp vectorizationModule,
                                    ModuleOp loweringModule);

  /// Update call sites in the module to use memref arguments instead of tensors
  /// after the function has been bufferized with bufferize_function_boundaries=true
  void updateCallSites(ModuleOp module, StringRef funcName);

  /// Unwrap nested module structure if present
  /// Some transforms may wrap their result in an additional module, which would
  /// cause subsequent transforms like one_shot_bufferize to not process the
  /// inner function
  void unwrapNestedModule(OwningOpRef<ModuleOp> &module, StringRef funcName);
};

} // end anonymous namespace

void CpuLowerVerifierPass::dumpBeforeTransform(ModuleOp targetModule,
                                                   ModuleOp transformModule,
                                                   StringRef funcName,
                                                   StringRef phaseName) {
  // Create filename: /tmp/cpu_verifier_<funcname>_<phase>.mlir
  std::string filename =
      "/tmp/cpu_verifier_" + funcName.str() + "_" + phaseName.str() + ".mlir";

  std::error_code ec;
  llvm::raw_fd_ostream outFile(filename, ec, llvm::sys::fs::OF_Text);

  if (ec) {
    LLVM_DEBUG(llvm::dbgs() << "Warning: Could not open dump file " << filename
                            << ": " << ec.message() << "\n");
    return;
  }

  outFile << "// =============================================================\n";
  outFile << "// CPU Verifier Dump: " << funcName << " - " << phaseName << " phase\n";
  outFile << "// =============================================================\n\n";

  outFile << "// --- Target IR (before " << phaseName << ") ---\n";
  targetModule.print(outFile);
  outFile << "\n\n";

  outFile << "// --- Transform Sequence (" << phaseName << ") ---\n";
  transformModule.print(outFile);
  outFile << "\n";

  LLVM_DEBUG(llvm::dbgs() << "Dumped IR and transform to: " << filename << "\n");
}

LogicalResult
CpuLowerVerifierPass::applyTransformSequence(ModuleOp tempModule,
                                                 ModuleOp transformModule,
                                                 StringRef sequenceName) {
  // Find the transform entry point
  transform::TransformOpInterface entryPoint =
      transform::detail::findTransformEntryPoint(tempModule, transformModule);
  if (!entryPoint) {
    return tempModule.emitError("Could not find transform entry point for ")
           << sequenceName;
  }

  // Apply the transform sequence to the temporary module
  transform::TransformOptions options;
  if (failed(transform::applyTransformNamedSequence(
          tempModule, entryPoint, transformModule, options))) {
    return tempModule.emitError("Transform interpreter failed for ")
           << sequenceName;
  }

  return success();
}

void CpuLowerVerifierPass::unwrapNestedModule(OwningOpRef<ModuleOp> &module,
                                                  StringRef funcName) {
  // Check if there's a nested module inside the outer module
  // This can happen when some transforms wrap their result in a new module
  ModuleOp nestedModule = nullptr;
  for (Operation &op : module->getBody()->getOperations()) {
    if (auto nested = dyn_cast<ModuleOp>(&op)) {
      nestedModule = nested;
      break;
    }
  }

  if (!nestedModule) {
    return; // No nested module, nothing to do
  }

  LLVM_DEBUG(llvm::dbgs() << "  Unwrapping nested module structure\n");

  // Find the function inside the nested module
  func::FuncOp funcOp = nullptr;
  nestedModule.walk([&](func::FuncOp f) {
    if (f.getName() == funcName)
      funcOp = f;
  });

  if (!funcOp) {
    // Function not found in nested module, leave as-is
    return;
  }

  // Create a new clean module with just the function
  MLIRContext *ctx = module->getContext();
  Location loc = module->getLoc();
  OwningOpRef<ModuleOp> newModule = ModuleOp::create(loc);

  // Clone the function into the new module
  OpBuilder builder(ctx);
  builder.setInsertionPointToStart(newModule->getBody());
  builder.clone(*funcOp.getOperation());

  // Replace the old module with the new one
  module = std::move(newModule);
}

void CpuLowerVerifierPass::updateCallSites(ModuleOp module,
                                               StringRef funcName) {
  // Find the lowered function to get its signature
  auto loweredFunc = module.lookupSymbol<func::FuncOp>(funcName);
  if (!loweredFunc) {
    LLVM_DEBUG(llvm::dbgs() << "  Could not find lowered function " << funcName
                            << "\n");
    return;
  }

  // Find all call ops that call the target function
  SmallVector<func::CallOp> callsToUpdate;
  module.walk([&](func::CallOp callOp) {
    if (callOp.getCallee() == funcName)
      callsToUpdate.push_back(callOp);
  });

  if (callsToUpdate.empty()) {
    LLVM_DEBUG(llvm::dbgs() << "  No call sites found for " << funcName << "\n");
    return;
  }

  LLVM_DEBUG(llvm::dbgs() << "  Updating " << callsToUpdate.size()
                          << " call site(s) for " << funcName << "\n");

  for (func::CallOp callOp : callsToUpdate) {
    OpBuilder builder(callOp);
    Location loc = callOp.getLoc();

    // Collect the source memrefs from the to_tensor operands
    SmallVector<Value> memrefArgs;
    SmallVector<bufferization::ToTensorOp> toTensorOps;

    for (Value operand : callOp.getOperands()) {
      auto toTensorOp = operand.getDefiningOp<bufferization::ToTensorOp>();
      if (toTensorOp) {
        memrefArgs.push_back(toTensorOp.getOperand());
        toTensorOps.push_back(toTensorOp);
      } else {
        // If the operand is not from a to_tensor, it might already be a memref
        // or something else - this shouldn't happen in our expected pattern
        LLVM_DEBUG(llvm::dbgs()
                   << "  Warning: operand is not from to_tensor: " << operand
                   << "\n");
        memrefArgs.push_back(operand);
      }
    }

    // Create a new call with the lowered function's return types
    // With bufferize_function_boundaries=true, the function signature changes
    // from (tensor, tensor, tensor) -> tensor to (memref, memref, memref) -> memref
    auto newCall = builder.create<func::CallOp>(
        loc, funcName, loweredFunc.getResultTypes(), memrefArgs);

    // Find and remove the to_buffer and copy ops that use the old result
    // The new call returns a memref directly, so we don't need to_buffer anymore
    if (!callOp.getResults().empty()) {
      Value oldResult = callOp.getResult(0);
      for (Operation *user : llvm::make_early_inc_range(oldResult.getUsers())) {
        if (auto toBufferOp = dyn_cast<bufferization::ToBufferOp>(user)) {
          // Replace uses of to_buffer result with the new call's result
          // (if the function returns a memref)
          if (!newCall.getResults().empty()) {
            toBufferOp.getResult().replaceAllUsesWith(newCall.getResult(0));
          }
          // Find and remove the copy that uses the to_buffer result
          Value buffer = toBufferOp.getResult();
          for (Operation *bufUser :
               llvm::make_early_inc_range(buffer.getUsers())) {
            if (auto copyOp = dyn_cast<memref::CopyOp>(bufUser)) {
              copyOp.erase();
            }
          }
          toBufferOp.erase();
        }
      }
    }

    // Erase the old call
    callOp.erase();

    // Erase the to_tensor ops if they have no other uses
    for (auto toTensorOp : toTensorOps) {
      if (toTensorOp.use_empty())
        toTensorOp.erase();
    }
  }
}

LogicalResult
CpuLowerVerifierPass::lowerSingleFunction(func::FuncOp func,
                                              ModuleOp preModule,
                                              ModuleOp optimizationModule,
                                              ModuleOp postModule,
                                              ModuleOp vectorizationModule,
                                              ModuleOp loweringModule) {
  MLIRContext *ctx = &getContext();
  Location loc = func.getLoc();
  StringRef funcName = func.getName();

  LLVM_DEBUG(llvm::dbgs() << "Lowering CPU verifier function: " << funcName
                          << "\n");

  // Step 1: Create a temporary module containing only this function
  OwningOpRef<ModuleOp> tempModule = ModuleOp::create(loc);

  // Step 2: Clone the function into the temporary module
  IRMapping mapping;
  Operation *clonedOp = func->clone(mapping);
  auto clonedFunc = cast<func::FuncOp>(clonedOp);
  tempModule->push_back(clonedFunc);

  // ===== Phase 1: Pre → Optimization → Post =====
  LLVM_DEBUG(llvm::dbgs() << "  Phase 1: Optimization\n");

  // Pre-sequence (canonicalize + cse)
  LLVM_DEBUG(llvm::dbgs() << "    Applying pre sequence...\n");
  dumpBeforeTransform(tempModule.get(), preModule, funcName, "pre_optimization");
  if (failed(applyTransformSequence(tempModule.get(), preModule, "pre"))) {
    return func.emitError("Pre transform failed before optimization");
  }

  // Optimization sequence (tiling)
  LLVM_DEBUG(llvm::dbgs() << "    Applying optimization sequence...\n");
  dumpBeforeTransform(tempModule.get(), optimizationModule, funcName,
                      "optimization");
  if (failed(applyTransformSequence(tempModule.get(), optimizationModule,
                                    "optimization"))) {
    return func.emitError("Optimization transform failed for function");
  }

  // Unwrap any nested module structure created by the transform
  unwrapNestedModule(tempModule, funcName);

  // Post-sequence (tiling canonicalization + LICM + hoisting)
  LLVM_DEBUG(llvm::dbgs() << "    Applying post sequence...\n");
  dumpBeforeTransform(tempModule.get(), postModule, funcName, "post_optimization");
  if (failed(applyTransformSequence(tempModule.get(), postModule, "post"))) {
    return func.emitError("Post transform failed after optimization");
  }

  // ===== Phase 2: Pre → Vectorization → Post =====
  LLVM_DEBUG(llvm::dbgs() << "  Phase 2: Vectorization\n");

  // Pre-sequence
  LLVM_DEBUG(llvm::dbgs() << "    Applying pre sequence...\n");
  dumpBeforeTransform(tempModule.get(), preModule, funcName, "pre_vectorization");
  if (failed(applyTransformSequence(tempModule.get(), preModule, "pre"))) {
    return func.emitError("Pre transform failed before vectorization");
  }

  // Vectorization sequence
  LLVM_DEBUG(llvm::dbgs() << "    Applying vectorization sequence...\n");
  dumpBeforeTransform(tempModule.get(), vectorizationModule, funcName,
                      "vectorization");
  if (failed(applyTransformSequence(tempModule.get(), vectorizationModule,
                                    "vectorization"))) {
    return func.emitError("Vectorization transform failed for function");
  }

  // Unwrap any nested module structure
  unwrapNestedModule(tempModule, funcName);

  // Post-sequence
  LLVM_DEBUG(llvm::dbgs() << "    Applying post sequence...\n");
  dumpBeforeTransform(tempModule.get(), postModule, funcName, "post_vectorization");
  if (failed(applyTransformSequence(tempModule.get(), postModule, "post"))) {
    return func.emitError("Post transform failed after vectorization");
  }

  // ===== Phase 3: Pre → Lowering → Post =====
  LLVM_DEBUG(llvm::dbgs() << "  Phase 3: Lowering\n");

  // Pre-sequence
  LLVM_DEBUG(llvm::dbgs() << "    Applying pre sequence...\n");
  dumpBeforeTransform(tempModule.get(), preModule, funcName, "pre_lowering");
  if (failed(applyTransformSequence(tempModule.get(), preModule, "pre"))) {
    return func.emitError("Pre transform failed before lowering");
  }

  // Lowering sequence (bufferization + LLVM lowering)
  LLVM_DEBUG(llvm::dbgs() << "    Applying lowering sequence...\n");
  dumpBeforeTransform(tempModule.get(), loweringModule, funcName, "lowering");
  if (failed(applyTransformSequence(tempModule.get(), loweringModule,
                                    "lowering"))) {
    return func.emitError("Lowering transform failed for function");
  }

  // Post-sequence after lowering
  LLVM_DEBUG(llvm::dbgs() << "    Applying post sequence...\n");
  dumpBeforeTransform(tempModule.get(), postModule, funcName, "post_lowering");
  if (failed(applyTransformSequence(tempModule.get(), postModule, "post"))) {
    return func.emitError("Post transform failed after lowering");
  }

  // Step 5: Get the lowered function from the temporary module
  // After lowering to LLVM, the function is now LLVM::LLVMFuncOp
  func::FuncOp loweredFunc = nullptr;
  tempModule->walk([&](func::FuncOp f) { loweredFunc = f; });

  if (!loweredFunc) {
    return func.emitError("Could not find lowered function in temporary module");
  }

  // Step 6: Replace the original function with the lowered one
  ModuleOp parentModule = func->getParentOfType<ModuleOp>();
  OpBuilder builder(ctx);
  builder.setInsertionPointToStart(parentModule.getBody());

  // Copy all top-level operations from tempModule to parentModule
  // (globals, function declarations, etc.) using SymbolOpInterface for genericity
  for (Operation &op : tempModule->getBody()->getOperations()) {
    // Skip module terminator
    if (op.hasTrait<OpTrait::IsTerminator>())
      continue;

    // Check if this is a symbol-defining operation
    if (auto symbolOp = dyn_cast<SymbolOpInterface>(&op)) {
      StringRef symName = symbolOp.getName();

      // Skip the lowered function itself (we handle it separately below)
      if (symName == funcName)
        continue;

      // Check if symbol already exists in parent module
      Operation *existing = parentModule.lookupSymbol(symName);
      if (existing) {
        // Special case: replace func.func with llvm.func (LLVM version is preferred)
        if (isa<func::FuncOp>(existing) && isa<LLVM::LLVMFuncOp>(&op)) {
          existing->erase();
        } else {
          // Symbol already exists, skip to avoid duplicates
          continue;
        }
      }

      builder.clone(op);
      LLVM_DEBUG(llvm::dbgs() << "  Copied symbol: " << symName << "\n");
    }
  }

  // Clone the lowered function back to the original module
  builder.setInsertionPoint(func);
  IRMapping backMapping;
  Operation *finalOp = loweredFunc->clone(backMapping);
  builder.insert(finalOp);

  // Erase the original function
  func.erase();

  // Step 7: Update call sites to use memref arguments instead of tensors
  // This is needed because bufferize_function_boundaries=true changes the
  // function signature from tensors to memrefs
  updateCallSites(parentModule, funcName);

  LLVM_DEBUG(llvm::dbgs() << "Successfully lowered: " << funcName << "\n");
  return success();
}

void CpuLowerVerifierPass::runOnOperation() {
  ModuleOp module = getOperation();
  MLIRContext *ctx = &getContext();

  // Collect all functions with the cpu_verifier attribute
  // We collect them first because we'll be modifying the module
  SmallVector<func::FuncOp> cpuVerifierFuncs;
  module.walk([&](func::FuncOp func) {
    if (isCpuVerifierFunc(func))
      cpuVerifierFuncs.push_back(func);
  });

  if (cpuVerifierFuncs.empty()) {
    LLVM_DEBUG(llvm::dbgs() << "No CPU verifier functions found\n");
    return;
  }

  LLVM_DEBUG(llvm::dbgs() << "Found " << cpuVerifierFuncs.size()
                          << " CPU verifier function(s)\n");

  // Parse all transform modules
  // The transform dialect extensions are registered in getDependentDialects()

  // Pre-sequence (canonicalize + cse)
  OwningOpRef<ModuleOp> preModule =
      parseSourceString<ModuleOp>(kPreSequence, ctx);
  if (!preModule) {
    emitError(UnknownLoc::get(ctx))
        << "Failed to parse pre transform sequence for CPU verifier";
    return signalPassFailure();
  }

  // Post-sequence (tiling canonicalization + LICM + hoisting)
  OwningOpRef<ModuleOp> postModule =
      parseSourceString<ModuleOp>(kPostSequence, ctx);
  if (!postModule) {
    emitError(UnknownLoc::get(ctx))
        << "Failed to parse post transform sequence for CPU verifier";
    return signalPassFailure();
  }

  // Optimization transform module (tiling)
  OwningOpRef<ModuleOp> optimizationModule =
      parseSourceString<ModuleOp>(kOptimizationSequence, ctx);
  if (!optimizationModule) {
    emitError(UnknownLoc::get(ctx))
        << "Failed to parse optimization transform sequence for CPU verifier";
    return signalPassFailure();
  }

  // Vectorization transform module
  OwningOpRef<ModuleOp> vectorizationModule =
      parseSourceString<ModuleOp>(kVectorizationSequence, ctx);
  if (!vectorizationModule) {
    emitError(UnknownLoc::get(ctx))
        << "Failed to parse vectorization transform sequence for CPU verifier";
    return signalPassFailure();
  }

  // Lowering transform module (bufferization + LLVM)
  OwningOpRef<ModuleOp> loweringModule =
      parseSourceString<ModuleOp>(kLoweringSequence, ctx);
  if (!loweringModule) {
    emitError(UnknownLoc::get(ctx))
        << "Failed to parse lowering transform sequence for CPU verifier";
    return signalPassFailure();
  }

  // Lower each function in isolation using the transform interpreter
  // Pipeline: Pre → Optimization → Post → Pre → Vectorization → Post → Pre → Lowering → Post
  for (func::FuncOp func : cpuVerifierFuncs) {
    if (failed(lowerSingleFunction(func, preModule.get(),
                                   optimizationModule.get(), postModule.get(),
                                   vectorizationModule.get(),
                                   loweringModule.get()))) {
      return signalPassFailure();
    }
  }

  // Ensure memrefCopy declaration exists if any llvm.call @memrefCopy was generated
  // The MemRefToLLVM conversion generates calls to memrefCopy but doesn't create
  // the declaration automatically
  bool hasMemrefCopyCall = false;
  module.walk([&](LLVM::CallOp callOp) {
    if (callOp.getCallee() && *callOp.getCallee() == "memrefCopy")
      hasMemrefCopyCall = true;
  });

  if (hasMemrefCopyCall && !module.lookupSymbol<LLVM::LLVMFuncOp>("memrefCopy")) {
    OpBuilder builder(ctx);
    builder.setInsertionPointToStart(module.getBody());

    // memrefCopy signature: void memrefCopy(i64 elemSize, ptr src, ptr dst)
    auto ptrType = LLVM::LLVMPointerType::get(ctx);
    auto i64Type = IntegerType::get(ctx, 64);
    auto voidType = LLVM::LLVMVoidType::get(ctx);
    auto funcType = LLVM::LLVMFunctionType::get(voidType, {i64Type, ptrType, ptrType});

    builder.create<LLVM::LLVMFuncOp>(module.getLoc(), "memrefCopy", funcType,
                                     LLVM::Linkage::External);
    LLVM_DEBUG(llvm::dbgs() << "Created memrefCopy declaration\n");
  }

  LLVM_DEBUG(llvm::dbgs() << "CPU verifier lowering completed\n");
}
